(()=>{
const P=ChroneaProject,T=ChroneaTime,D=ChroneaAdapters,results=[],assert=x=>{if(!x)throw Error('Assertion')},equal=(a,b)=>assert(JSON.stringify(a)===JSON.stringify(b)),test=(name,fn)=>{try{fn();results.push({name,ok:true})}catch(error){results.push({name,ok:false,error:String(error)})}},reject=fn=>{let no=false;try{fn()}catch{no=true}assert(no)};
const p=P.create(),t=p.timelines[0],a=P.event('Avancé',{kind:'interval',start:{value:{year:1998},precision:'year',qualifier:'exact',notBefore:{year:1998,month:3},notAfter:{year:1998,month:6}},end:{value:{year:2001},precision:'year',qualifier:'approximate'}}),b=P.event('Exact',{kind:'point',start:{value:{year:2012,month:7,day:3},precision:'day',qualifier:'exact'},end:null});t.events=[a,b];t.relations=[{id:P.id(),sourceId:a.id,targetId:b.id,type:'causes',direction:'directed',note:'Lien'}];
test('Phase 6 : CSV V3 conserve bornes indépendantes et relations',()=>{const csv=D.csv(p,t.id),r=D.readCSV(csv.text);equal(r.project,p)});
test('Phase 6 : mapping CSV montre erreurs de dates par ligne',()=>{const r=D.readCSV('nom;date\nValide;2012-07\nImpossible;2023-02-29','Test',{title:'0',start:'1'});assert(r.errors.length===1&&r.errors[0].line===3&&r.project.timelines[0].events.length===1)});
test('Phase 6 : mapping EDTF approximation et ouvert',()=>{const r=D.readCSV('nom,date\nVers,2012-07~\nAvant,../1980','Test',{title:'0',start:'1'});assert(!r.errors.length);assert(r.project.timelines[0].events[0].temporal.start.qualifier==='approximate'&&r.project.timelines[0].events[1].temporal.kind==='openInterval')});
test('Phase 6 : mapping numérique décimal et direction',()=>{const r=D.readCSV('nom,start,end\nCycle,12.5,10','Test',{title:'0',start:'1',end:'2',mode:'numeric',unit:'cycle',direction:-1});assert(!r.errors.length);assert(r.project.timelines[0].events[0].temporal.start.value===12.5)});
test('Phase 6 : ajout indépendant rebase toutes références',()=>{const r=D.rebase(p,new Map());assert(r.project.id!==p.id);P.validate(r.project);assert(r.project.timelines[0].relations[0].sourceId===r.project.timelines[0].events[0].id)});
test('Phase 6 : fusion par identifiant externe sans égalité de titre',()=>{const original=P.create(),ot=original.timelines[0],e=P.clone(b);e.externalIds.csv='42';ot.events=[e];const incoming=P.create(),it=incoming.timelines[0],updated=P.clone(e);updated.title='Mise à jour';it.events=[updated];const r=D.merge(original,new Map(),incoming,new Map(),ot.id,true);assert(r.project.timelines[0].events.length===1&&r.project.timelines[0].events[0].id===e.id&&r.project.timelines[0].events[0].title==='Mise à jour');equal(original.timelines[0].events[0].title,b.title)});
test('Phase 6 : correspondance externe ambiguë refusée',()=>{const q=P.clone(p);q.timelines[0].events.forEach(e=>e.externalIds.csv='42');reject(()=>D.merge(q,new Map(),p,new Map(),t.id,true))});
const js={'@type':'Event',uid:'test@example.org',updated:'2026-09-18T10:00:00Z',title:'Réunion',start:'2024-03-30T12:00:00',timeZone:'Europe/Paris',duration:'P1DT1H',description:'Notes',keywords:{voyage:true}};
test('Phase 6 : JSCalendar durée jours puis heures au changement d’heure',()=>{const r=D.readJSCalendar(js),e=r.project.timelines[0].events[0];assert(e.temporal.end.value.day===31&&e.temporal.end.value.hour===13);assert(e.externalIds.jscalendar===js.uid)});
test('Phase 6 : JSCalendar round-trip instants, UID et texte',()=>{const r=D.readJSCalendar(js),out=D.jscalendar(r.project,r.project.timelines[0].id),again=D.readJSCalendar(out.data),x=r.project.timelines[0].events[0],y=again.project.timelines[0].events[0];assert(out.skipped.length===0);equal(T.range(x.temporal,r.project.timeSystems[0]),T.range(y.temporal,again.project.timeSystems[0]));equal(x.externalIds,y.externalIds);equal(x.summary,y.summary)});
test('Phase 6 : JSCalendar all-day conserve horaire sous-jacent',()=>{const r=D.readJSCalendar({...js,start:'2024-04-01T09:00:00',duration:'P1D',showWithoutTime:true});assert(r.project.timelines[0].events[0].temporal.start.value.hour===9);assert(D.jscalendar(r.project,r.project.timelines[0].id).data.entries[0].showWithoutTime)});
test('Phase 6 : JSCalendar refuse récurrence et heure impossible',()=>{reject(()=>D.readJSCalendar({...js,recurrenceRules:[]}));reject(()=>D.readJSCalendar({...js,start:'2024-03-31T02:30:00'}))});
test('Phase 6 : JSCalendar omet honnêtement les temporalités avancées',()=>{const r=D.jscalendar(p,t.id);assert(r.skipped.length===1&&r.data.entries.length===1)});
test('Phase 6 : enveloppe native version future refusée',()=>reject(()=>P.read({app:'Chronéa',schemaVersion:99,project:p})));
test('Phase 8 : JSON-LD ne transforme pas une possibilité ou un ouvert en date certaine',()=>{const q=P.clone(p),e=P.event('Après',{kind:'openInterval',start:{value:{year:2020,month:3,day:2},precision:'day',qualifier:'exact'},end:null});q.timelines[0].events.push(e);const out=D.jsonld(q,t.id);assert(!out.hasPart[0].startDate&&out.hasPart[1].startDate==='2012-07-03'&&!out.hasPart[2].startDate&&out.hasPart[2].description.includes('après'))});
return results;
})()
