/* Adaptateurs explicites : les formats externes ne deviennent jamais le modèle métier. */
const ChroneaAdapters=(()=>{
 'use strict';const P=ChroneaProject,T=ChroneaTime,C=ChroneaCore;
 const fail=m=>{throw Error(m)};
 const CAPABILITIES={native:{temporal:'Conservé',systems:'Conservé',media:'Conservé',relations:'Conservé',sources:'Conservé'},csv:{temporal:'Conservé (colonnes JSON)',systems:'Conservé',media:'Médias locaux omis ; références distantes conservées',relations:'Conservé',sources:'Conservé'},ics:{temporal:'Dates complètes exactes sans possibilités ; ouverts et autres repères omis',systems:'Grégorien seulement',media:'Omis',relations:'UID RELATED-TO seulement',sources:'Omis'},jscalendar:{temporal:'Dates complètes exactes ; autres repères omis',systems:'Grégorien seulement',media:'Omis',relations:'Transformé : relatedTo par UID ; nuances typées omises',sources:'Omis'},timelinejs:{temporal:'Partiel ; nuances transformées en libellé',systems:'Grégorien seulement',media:'Un média par événement',relations:'Omis',sources:'Omis'},preceden:{temporal:'Partiel ; qualifications limitées',systems:'Grégorien seulement',media:'Omis',relations:'Omis',sources:'Transformées en notes'},jsonld:{temporal:'Dates exactes grégoriennes seulement',systems:'Grégorien seulement',media:'Omis',relations:'Omis',sources:'Omis'}};
 function csv(project,timelineId){const p=P.subset(project,timelineId),t=p.timelines[0],local=new Set(p.media.filter(m=>!m.remoteUrl).map(m=>m.id));p.media=p.media.filter(m=>m.remoteUrl);t.events.forEach(e=>e.mediaIds=e.mediaIds.filter(id=>!local.has(id)));const events=t.events;t.events=[];const rows=[['schema_version','project_json','event_json','title','summary','type','place','tags_json','temporal_json','display_date','external_ids_json']];events.forEach((e,i)=>rows.push([3,i===0?JSON.stringify(p):'',JSON.stringify(e),e.title,e.summary,e.type,e.place,JSON.stringify(e.tags),JSON.stringify(e.temporal),e.displayDate,JSON.stringify(e.externalIds)]));if(!events.length)rows.push([3,JSON.stringify(p),'','','','','','','','','']);return {text:'\uFEFF'+C.csvRows(rows),omitted:local.size};}
 function readCSV(text,name='CSV',mapping=null){const rows=C.parseCSV(text),headers=rows[0],col=h=>headers.indexOf(h),errors=[];
  if(col('schema_version')>=0&&col('project_json')>=0){const row=rows.find((r,i)=>i&&r[col('project_json')]);if(!row)fail('Métadonnées CSV V3 absentes.');const p=JSON.parse(row[col('project_json')]);for(const r of rows.slice(1)){if(!r[col('event_json')])continue;const e=JSON.parse(r[col('event_json')]);for(const [h,key]of [['title','title'],['summary','summary'],['type','type'],['place','place'],['display_date','displayDate']])if(col(h)>=0)e[key]=r[col(h)];for(const [h,key]of [['temporal_json','temporal'],['tags_json','tags'],['external_ids_json','externalIds']])if(col(h)>=0)e[key]=JSON.parse(r[col(h)]);p.timelines[0].events.push(e);}P.validate(p);return {project:p,assets:new Map(),warnings:['CSV V3 : les médias locaux nécessitent le paquet natif.'],errors};}
  if(!mapping){const parsed=C.fromCSV(text,P.id,name);return {...P.fromLegacy({version:2,currentId:parsed.timeline.id,timelines:[parsed.timeline]}),assets:new Map(),errors,warnings:['Colonnes omises : '+(parsed.ignoredColumns.join(', ')||'aucune')]};}
  const p=P.create(name),t=p.timelines[0];t.title=name;if(mapping.mode==='numeric'){p.timeSystems=[{id:P.id(),type:'numeric',name:'Axe CSV',definition:{unit:mapping.unit||'cycle',direction:Number(mapping.direction)||1}}];t.timeSystemId=p.timeSystems[0].id;}
  const system=p.timeSystems[0],get=(r,key)=>mapping[key]!==undefined&&mapping[key]!==''?r[Number(mapping[key])]:'';
  for(const [i,r]of rows.slice(1).entries()){try{const title=get(r,'title').trim();if(!title)fail('Titre absent.');const raw=get(r,'start'),value=mapping.mode!=='numeric'&&/[~?]|\/\.\.|\.\.\//.test(raw)?null:T.parseValue(raw,system),end=T.parseValue(get(r,'end'),system);let temporal={kind:end!==null?'interval':'point',start:value!==null?{value,precision:T.precision(value,system),qualifier:'exact'}:null,end:end!==null?{value:end,precision:T.precision(end,system),qualifier:'exact'}:null};if(mapping.mode!=='numeric'&&raw&&/[~?]|\/\.\.|\.\.\//.test(raw))temporal=T.legacyTemporal(C.parseEDTF(raw),'calendar');T.validateTemporal(temporal,system);const e=P.event(title,temporal);e.summary=get(r,'summary');e.markdown=get(r,'markdown');e.place=get(r,'place');e.tags=get(r,'tags').split(',').map(x=>x.trim()).filter(Boolean);const external=get(r,'id');if(external){e.externalIds.csv=external;if(t.events.some(e=>e.externalIds.csv===external))fail('Identifiant externe dupliqué.');}const laneName=get(r,'lane');if(laneName){let lane=t.lanes.find(l=>l.name===laneName);if(!lane){lane={id:P.id(),name:laneName,order:t.lanes.length,visible:true,color:e.color};t.lanes.push(lane);}e.laneId=lane.id;}const source=get(r,'source');if(source){const s={id:P.id(),title:source,citation:source,type:'csv'};p.sources.push(s);e.sourceIds=[s.id];}t.events.push(e);}catch(error){errors.push({line:i+2,message:error.message})}}
  P.validate(p);return {project:p,assets:new Map(),errors,warnings:['CSV mappé : texte UTF-8 ; les colonnes sans destination sont omises.']};
 }
 function fromInstant(ms,tzid){if(tzid){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:tzid,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms)).map(x=>[x.type,x.value]));return {year:Number(parts.year),month:Number(parts.month),day:Number(parts.day),hour:Number(parts.hour),minute:Number(parts.minute),second:Number(parts.second),tzid};}const d=new Date(ms);return {year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate(),hour:d.getUTCHours(),minute:d.getUTCMinutes(),second:d.getUTCSeconds()};}
 function duration(text){const m=String(text).match(/^P(?:(\d+)W)?(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/);if(!m||!m.slice(1).some(x=>x!==undefined)||text.endsWith('T'))fail('Durée JSCalendar non prise en charge (secondes entières).');const days=Number(m[1]||0)*7+Number(m[2]||0),seconds=Number(m[3]||0)*3600+Number(m[4]||0)*60+Number(m[5]||0);if(!Number.isSafeInteger(days)||!Number.isSafeInteger(seconds))fail('Durée hors plage.');return {days,seconds};}
 function readJSCalendar(input){C.checkTree(input);const p=P.create('JSCalendar'),t=p.timelines[0],items=input['@type']==='Group'?input.entries:[input],warnings=[];if(!Array.isArray(items))fail('Group JSCalendar sans entries.');const uidIds=new Map();
  for(const item of items){if(item['@type']!=='Event'||typeof item.uid!=='string'||!item.uid||typeof item.updated!=='string')fail('Event JSCalendar : uid/updated obligatoires.');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?Z$/.test(item.updated))fail('UTCDateTime updated JSCalendar invalide.');T.parseValue(item.updated.replace(/\.\d+(?=Z$)/,''),p.timeSystems[0]);if(item.showWithoutTime!==undefined&&typeof item.showWithoutTime!=='boolean')fail('showWithoutTime doit être booléen.');if(item.timeZone!==undefined&&item.timeZone!==null&&typeof item.timeZone!=='string')fail('timeZone invalide.');if(item.keywords&&(!item.keywords||typeof item.keywords!=='object'||Array.isArray(item.keywords)||Object.values(item.keywords).some(value=>value!==true)))fail('keywords JSCalendar doit être un ensemble true.');if(item.recurrenceRules||item.recurrenceOverrides||item.excludedRecurrenceRules||item.timeZones)fail('Récurrences et fuseaux personnalisés JSCalendar non pris en charge.');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/.test(item.start))fail('LocalDateTime JSCalendar invalide ou fractionnaire.');if(uidIds.has(item.uid))fail('UID JSCalendar dupliqué.');if(item.descriptionContentType&&item.descriptionContentType!=='text/plain')fail('Description JSCalendar : seul text/plain est pris en charge.');const sys=p.timeSystems[0],a=T.parseValue(item.start+(item.timeZone?'['+item.timeZone+']':''),sys),d=duration(item.duration||'PT0S');const shifted={...a,...T.dayCivil(T.civilDay(a.year,a.month,a.day)+d.days)},end=fromInstant(C.icsInstant(T.icsEndpoint(shifted))+d.seconds*1000,a.tzid);T.validateValue(end,sys);const endpoint=value=>({value,precision:T.precision(value,sys),qualifier:'exact'}),e=P.event(item.title||'Sans titre',{kind:d.days||d.seconds?'interval':'point',start:endpoint(a),end:d.days||d.seconds?endpoint(end):null});e.summary=item.description||'';e.tags=Object.keys(item.keywords||{}).filter(k=>item.keywords[k]);e.place=Object.values(item.locations||{}).map(l=>l.name).filter(Boolean).join(', ');e.externalIds.jscalendar=item.uid;e.metadata={jscalendarOriginal:P.clone(item),showWithoutTime:!!item.showWithoutTime};uidIds.set(item.uid,e.id);t.events.push(e);const supported=['@type','uid','updated','created','title','description','descriptionContentType','start','duration','timeZone','showWithoutTime','keywords','locations','relatedTo'];const other=Object.keys(item).filter(k=>!supported.includes(k));if(other.length)warnings.push(item.uid+' : propriétés conservées en provenance mais non éditées : '+other.join(', '));}
  for(const e of t.events){const relations=e.metadata.jscalendarOriginal.relatedTo||{};for(const [uid,relation]of Object.entries(relations)){const targetId=uidIds.get(uid);if(!targetId||targetId===e.id){warnings.push('Relation externe non résolue : '+uid);continue;}const types=Object.keys(relation.relation||{});t.relations.push({id:P.id(),sourceId:e.id,targetId,type:types.includes('parent')?'dependsOn':'related',direction:'directed',note:''});}}
  P.validate(p);return {project:p,assets:new Map(),errors:[],warnings};
 }
 function jscalendar(project,timelineId){const t=project.timelines.find(t=>t.id===timelineId),system=project.timeSystems.find(s=>s.id===t.timeSystemId),entries=[],skipped=[];if(system.type!=='gregorian')return {data:{'@type':'Group',entries},skipped:t.events.map(e=>e.id)};
  for(const e of t.events){try{const ep=[e.temporal.start,e.temporal.end].filter(Boolean);if(e.temporal.kind==='openInterval'||!e.temporal.start||ep.some(x=>x.qualifier!=='exact'||x.notBefore!==undefined||x.notAfter!==undefined||x.value.day===undefined||x.value.month===undefined||x.value.year<1||x.value.year>9999))throw Error();const a=e.temporal.start.value,b=e.temporal.end?.value;let start={...a},seconds=0,days=0,show=a.hour===undefined;if(show){start.hour=0;start.minute=0;start.second=0;days=b?T.civilDay(b.year,b.month,b.day)-T.civilDay(a.year,a.month,a.day)+1:1;}else if(b){if(b.hour===undefined||(b.tzid||'')!==(a.tzid||'')||!!b.utc!==!!a.utc)throw Error();seconds=(C.icsInstant(T.icsEndpoint(b))-C.icsInstant(T.icsEndpoint(a)))/1000;if(!Number.isSafeInteger(seconds)||seconds<0)throw Error();}
   const uid=e.externalIds.jscalendar||e.externalIds.icalUid||e.id,original=e.metadata?.jscalendarOriginal||{},item={...P.clone(original),'@type':'Event',uid,updated:e.updatedAt,title:e.title,description:[e.summary,e.markdown].filter(Boolean).join('\n\n'),descriptionContentType:'text/plain',start:T.valueText({...start,second:start.second||0,utc:undefined,tzid:undefined},system),duration:show?'P'+days+'D':'PT'+seconds+'S',timeZone:a.utc?'Etc/UTC':a.tzid||null,showWithoutTime:e.metadata?.showWithoutTime??show,keywords:Object.fromEntries(e.tags.map(tag=>[tag,true]))};delete item.relatedTo;if(e.place)item.locations={place:{'@type':'Location',name:e.place}};entries.push(item);
  }catch{skipped.push(e.id)}}
  const included=new Set(entries.map(e=>e.uid)),byId=new Map(t.events.map(e=>[e.id,e.externalIds.jscalendar||e.externalIds.icalUid||e.id]));for(const item of entries){const e=t.events.find(e=>byId.get(e.id)===item.uid),rels=t.relations.filter(r=>r.sourceId===e.id&&included.has(byId.get(r.targetId)));if(rels.length)item.relatedTo=Object.fromEntries(rels.map(r=>[byId.get(r.targetId),{'@type':'Relation',relation:{[r.type==='dependsOn'?'parent':'next']:true}}]));}
  return {data:{'@type':'Group',entries},skipped};
 }
 /* Rebase complet : l'ajout indépendant évite les collisions de toutes les références. */
 function rebase(project,assets){const p=P.clone(project),map=new Map();[p,...p.timeSystems,...p.sources,...p.media,...p.timelines,...p.timelines.flatMap(t=>[...t.lanes,...t.spans,...t.events,...t.relations])].forEach(o=>{map.set(o.id,P.id());o.id=map.get(o.id)});const blobs=new Map();for(const m of p.media)if(!m.remoteUrl){const old=m.storageRef;m.storageRef='media/'+m.id;blobs.set(m.storageRef,assets.get(old))}for(const t of p.timelines){t.timeSystemId=map.get(t.timeSystemId);for(const e of [...t.events,...t.spans])if(e.laneId)e.laneId=map.get(e.laneId);for(const e of t.events){e.mediaIds=e.mediaIds.map(x=>map.get(x));e.sourceIds=e.sourceIds.map(x=>map.get(x))}for(const r of t.relations){r.sourceId=map.get(r.sourceId);r.targetId=map.get(r.targetId)}}P.validate(p);return {project:p,assets:blobs};}
 function merge(current,assets,incoming,incomingAssets,timelineId,update=false){const result=rebase(incoming,incomingAssets),p=P.clone(current),target=p.timelines.find(t=>t.id===timelineId),system=p.timeSystems.find(s=>s.id===target.timeSystemId),map=new Map(),warnings=[];if(result.project.timelines.some(t=>{const s=result.project.timeSystems.find(s=>s.id===t.timeSystemId);return s.type!==system.type||JSON.stringify(s.definition)!==JSON.stringify(system.definition)}))fail('La fusion nécessite des systèmes temporels identiques.');const identity=e=>Object.entries(e.externalIds).filter(([,value])=>value).map(([key,value])=>key+'::'+value),existing=new Map();if(update)for(const e of target.events)for(const key of identity(e)){if(existing.has(key))fail('Identifiant externe ambigu dans la destination.');existing.set(key,e.id)}const usedMatches=new Set();
  for(const t of result.project.timelines){for(const lane of t.lanes)target.lanes.push(lane);for(const span of t.spans)target.spans.push(span);for(const event of t.events){const matches=update?[...new Set(identity(event).map(key=>existing.get(key)).filter(Boolean))]:[];if(matches.length>1||matches.length&&usedMatches.has(matches[0]))fail('Correspondance externe ambiguë.');if(matches.length){const old=target.events.find(e=>e.id===matches[0]);usedMatches.add(old.id);map.set(event.id,old.id);Object.assign(old,event,{id:old.id,externalIds:{...old.externalIds,...event.externalIds}})}else{map.set(event.id,event.id);target.events.push(event)}}}
  for(const t of result.project.timelines)for(const r of t.relations){r.sourceId=map.get(r.sourceId);r.targetId=map.get(r.targetId);const same=target.relations.some(x=>x.type===r.type&&x.direction===r.direction&&(x.sourceId===r.sourceId&&x.targetId===r.targetId||x.direction==='undirected'&&x.sourceId===r.targetId&&x.targetId===r.sourceId));if(!same)target.relations.push(r)}p.sources.push(...result.project.sources);p.media.push(...result.project.media);const blobs=new Map([...assets,...result.assets]);P.validate(p);return {project:p,assets:blobs,warnings};}
 function jsonld(project,timelineId){const t=project.timelines.find(t=>t.id===timelineId),s=project.timeSystems.find(s=>s.id===t.timeSystemId),date=ep=>s.type==='gregorian'&&ep&&ep.qualifier==='exact'&&ep.notBefore===undefined&&ep.notAfter===undefined&&ep.value.year>=1&&ep.value.year<=9999&&ep.value.month!==undefined&&ep.value.day!==undefined?T.valueText(ep.value,s):null;return {'@context':'https://schema.org','@type':'EventSeries',name:t.title,hasPart:t.events.map(e=>({'@type':'Event',name:e.title,identifier:e.id,description:[e.summary,T.label(e.temporal,s)].filter(Boolean).join('\n'),...(e.temporal.kind!=='openInterval'&&date(e.temporal.start)?{startDate:date(e.temporal.start)}:{}),...(e.temporal.kind!=='openInterval'&&date(e.temporal.end)?{endDate:date(e.temporal.end)}:{})}))};}
 return {CAPABILITIES,jsonld,csv,readCSV,duration,readJSCalendar,jscalendar,rebase,merge};
})();
