/* Chronéa V3 — contrôleurs et vues. Le projet canonique est indépendant des préférences. */
(()=>{'use strict';
const P=ChroneaProject,T=ChroneaTime,C=ChroneaCore,S=ChroneaStorage,D=ChroneaAdapters,U=ChroneaPublication;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DEFAULT_PREFS={view:'vertical',density:'summary',theme:'parchment',style:'editorial',search:'',group:'',scaleCamera:null,rangeFilter:null,page:0,sort:'time',columns:'place,tags,edtf',relationType:''};
const App={version:'3.1.0',project:P.create(),assets:new Map(),prefs:{...DEFAULT_PREFS},currentId:null,store:new S.Store(),blocked:false,recoveryRaw:null,history:[],future:[],revision:0,savedRevision:0,saveTimer:null,saveQueue:Promise.resolve(),editingId:null,pendingMedia:[],fileReads:0,editorSession:0,returnFocus:null,urls:new Map(),fileHandle:null,lastFileSave:null,rangeCache:new WeakMap(),selected:new Set(),publication:null};
const projectIndexes=new WeakMap();
function projectIndex(){if(!projectIndexes.has(App.project))projectIndexes.set(App.project,{sources:new Map(App.project.sources.map(s=>[s.id,s])),media:new Map(App.project.media.map(m=>[m.id,m]))});return projectIndexes.get(App.project);}
const I18N={fr:{modified:'Modifié — sauvegarde locale en attente',loaded:'Projet chargé localement',saved:'Autosauvegardé localement',unavailable:'Cache local indisponible — enregistre un fichier projet',recovery:'Récupération nécessaire — original préservé'}};
function esc(value=''){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function slug(text){return String(text||'chronea').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'chronea';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function status(message){$('#saveStatus').textContent=message+(App.lastFileSave?' · fichier projet enregistré à '+App.lastFileSave:'');$('#recoveryBtn').classList.toggle('hidden',!App.blocked);}
function currentTimeline(){return App.project.timelines.find(t=>t.id===App.currentId)||App.project.timelines[0];}
function system(t=currentTimeline()){return App.project.timeSystems.find(s=>s.id===t.timeSystemId);}
function eventRange(e,t=currentTimeline()){let cached=App.rangeCache.get(e);if(!cached||cached.system!==t.timeSystemId){cached={system:t.timeSystemId,range:T.range(e.temporal,system(t))};App.rangeCache.set(e,cached);}return cached.range;}
function eventLabel(e,t=currentTimeline()){return e.displayDate||T.label(e.temporal,system(t));}
function eventLane(e,t=currentTimeline()){return t.lanes.find(l=>l.id===e.laneId)?.name||'';}
function sourceText(e){return [e.sourceIds.map(id=>projectIndex().sources.get(id)).filter(Boolean).map(s=>[s.title,s.citation,s.url,s.note].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join('\n')).join('\n\n'),e.metadata?.provenanceNote||''].filter(Boolean).join('\n\n');}
function markdown(text=''){
 let value=esc(text).replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/^> (.+)$/gm,'<blockquote>$1</blockquote>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>`<a href="${esc(C.safeUrl(url)||'#')}" target="_blank" rel="noopener noreferrer">${label}</a>`);
 let output='',list=false;for(const line of value.split('\n')){if(/^[-*] /.test(line)){if(!list){output+='<ul>';list=true;}output+='<li>'+line.slice(2)+'</li>';}else{if(list){output+='</ul>';list=false;}if(/^<(?:h\d|blockquote)/.test(line))output+=line;else if(line.trim())output+='<p>'+line+'</p>';}}return output+(list?'</ul>':'');
}
function parsedLinks(text=''){return text.split('\n').filter(s=>s.trim()).map(line=>{const parts=line.split('|'),url=C.safeUrl(parts.at(-1).trim());return {label:parts.length>1?parts[0].trim():line,url};}).filter(l=>l.url);}
function mediaUrl(m){if(m.remoteUrl)return C.safeUrl(m.remoteUrl);const key=m.storageRef+'::'+(m.checksum||m.id);if(!App.urls.has(key)){const blob=App.assets.get(m.storageRef);if(!blob)return '';App.urls.set(key,URL.createObjectURL(blob));}return App.urls.get(key);}
function revokeURLs(){for(const url of App.urls.values())URL.revokeObjectURL(url);App.urls.clear();}
function eventMedia(e){return e.mediaIds.map(id=>projectIndex().media.get(id)).filter(Boolean);}
function eventImage(e){const m=eventMedia(e).find(m=>!m.remoteUrl&&m.mimeType.startsWith('image/'));return m?{url:mediaUrl(m),alt:m.alt||e.title}:null;}
function relationsHTML(e,t=currentTimeline()){return t.relations.filter(r=>r.sourceId===e.id||r.targetId===e.id).map(r=>{const other=t.events.find(x=>x.id===(r.sourceId===e.id?r.targetId:r.sourceId));return other?`<button class="chip" data-open-event="${esc(other.id)}">${r.direction==='directed'?(r.sourceId===e.id?'→':'←'):'↔'} ${esc(ChroneaRelationLabels[r.type]||r.type)} · ${esc(other.title)}</button>`:'';}).join('');}
function card(e,t=currentTimeline()){
 const full=App.prefs.density==='full',compact=App.prefs.density==='compact',image=eventImage(e),lane=eventLane(e,t),edtf=T.edtf(e.temporal,system(t));
 return `<article class="event-card" style="--event:${esc(e.color)}" data-id="${esc(e.id)}">${image&&!compact?`<img class="media-thumb" src="${esc(image.url)}" alt="${esc(image.alt)}" loading="lazy">`:''}<div class="card-body">${e.temporal.kind==='interval'?'<span class="kind">Période</span>':''}${lane?`<div class="event-group">${esc(lane)}</div>`:''}<div class="date-label">${esc(eventLabel(e,t))}</div>${full&&edtf?`<div class="technical-date">EDTF ${esc(edtf)}</div>`:''}<button class="card-open" data-open-event="${esc(e.id)}"><h3>${esc(e.title)}</h3></button>${!compact&&e.summary?`<p>${esc(e.summary)}</p>`:''}${full&&e.markdown?`<div class="markdown">${markdown(e.markdown)}</div>`:''}<div class="event-meta">${e.tags.map(tag=>`<span class="chip">#${esc(tag)}</span>`).join('')}${e.place?`<span class="chip">${esc(e.place)}</span>`:''}${e.mediaIds.length?`<span class="chip">${e.mediaIds.length} fichier(s)</span>`:''}</div>${full?`<div class="event-meta">${relationsHTML(e,t)}</div>${sourceText(e)?`<div class="source-block">${esc(sourceText(e))}</div>`:''}<div class="event-meta">${parsedLinks(e.links).map(l=>`<a class="chip" href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(l.label)}</a>`).join('')}${eventMedia(e).map(m=>`<a class="chip" href="${esc(mediaUrl(m))}" ${m.remoteUrl?'target="_blank" rel="noopener noreferrer"':`download="${esc(m.name)}"`}>${m.remoteUrl?'En ligne : ':'↓ '}${esc(m.name)}</a>`).join('')}</div>`:''}</div></article>`;
}
function filteredEvents(t=currentTimeline()){
 const query=App.prefs.search.trim().toLowerCase(),camera=App.prefs.rangeFilter,lanes=new Map(t.lanes.map(l=>[l.id,l]));
 return t.events.filter(e=>{if(App.clusterFilter&&!App.clusterFilter.has(e.id))return false;const lane=lanes.get(e.laneId);if(lane&&!lane.visible)return false;if(App.prefs.group&&e.laneId!==App.prefs.group)return false;if(query&&![e.title,e.summary,e.markdown,e.displayDate,e.place,lane?.name,e.tags.join(' '),sourceText(e)].some(v=>String(v||'').toLowerCase().includes(query)))return false;if(camera){const r=eventRange(e,t);if(r.anchor===null||(r.min!==null&&r.min>camera.max)||(r.max!==null&&r.max<camera.min))return false;}return true;}).sort((a,b)=>App.prefs.view==='table'&&App.prefs.sort==='title'?a.title.localeCompare(b.title,'fr'):(eventRange(a,t).anchor??Infinity)-(eventRange(b,t).anchor??Infinity)||a.title.localeCompare(b.title,'fr'));
}
function bounds(t=currentTimeline()){let min=Infinity,max=-Infinity;for(const e of [...t.events,...t.spans]){const r=eventRange(e,t);for(const value of [r.min,r.max,r.anchor])if(Number.isFinite(value)){min=Math.min(min,value);max=Math.max(max,value);}}if(!Number.isFinite(min))return {min:0,max:1};if(min===max){min-=1;max+=1;}return {min,max};}
function coordinateLabel(value){const s=system();if(s.type==='numeric')return String(Number((value*(s.definition.direction??1)).toPrecision(8)));if(s.type==='gregorian')return T.valueText(T.dayCivil(value),s);return String(Number(value.toFixed(2)));}
function render(){
 const t=currentTimeline();App.currentId=t.id;document.documentElement.dataset.theme=App.prefs.theme;document.documentElement.dataset.style=App.prefs.style;
 $('#timelineSelect').innerHTML=App.project.timelines.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('');$('#timelineSelect').value=t.id;
 for(const [selector,key]of [['#searchInput','search'],['#densitySelect','density'],['#themeSelect','theme'],['#styleSelect','style']])if($(selector).value!==App.prefs[key])$(selector).value=App.prefs[key];
 $('#groupFilter').innerHTML='<option value="">Tous les fils</option>'+t.lanes.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');$('#groupFilter').value=App.prefs.group;
 syncScaleControls();$('#rangeFrom').value=App.prefs.rangeFilter?coordinateLabel(App.prefs.rangeFilter.min):'';$('#rangeTo').value=App.prefs.rangeFilter?coordinateLabel(App.prefs.rangeFilter.max):'';
 $$('#viewSeg button').forEach(b=>{const active=b.dataset.view===App.prefs.view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
 $('#compatibilityBanner').hidden=!isMixedProject();$('#addEventBtn').disabled=isMixedProject();$('#undoBtn').disabled=!App.history.length;$('#redoBtn').disabled=!App.future.length;$('#projectNameLabel').textContent=App.project.title;
 const events=filteredEvents(t);$('#countLabel').textContent=events.length+' / '+t.events.length;$('#printHeading').textContent=t.title;
 const host=$('#canvasInner');if(!t.events.length){host.innerHTML=`<div class="empty"><div class="empty-inner"><div class="orb"></div><h2>${esc(t.title)}</h2><p>Ajoute un premier repère, même si seule l’année est connue.</p><button class="btn primary" data-empty-add>Créer le premier événement</button> <button class="btn" data-empty-demo>Voir un exemple</button></div></div>`;return;}
 if(!events.length){host.innerHTML='<div class="empty"><div><h2>Aucun repère dans cette vue</h2><p>Efface la recherche ou utilise « Tout voir ».</p><button class="btn" data-reset-filters>Tout voir</button></div></div>';return;}
 const pageSize=200,page=App.prefs.view==='relations'?Math.max(0,App.prefs.page):Math.min(App.prefs.page,Math.floor((events.length-1)/pageSize));App.prefs.page=page;const visible=events.slice(page*pageSize,(page+1)*pageSize);
 if(App.prefs.view==='vertical')host.innerHTML='<div class="vertical-timeline">'+visible.map(e=>`<div class="v-row" style="--dot:${esc(e.color)}">${card(e,t)}<span class="dot"></span></div>`).join('')+'</div>';
 else if(App.prefs.view==='gallery')host.innerHTML='<div class="gallery">'+visible.map(e=>card(e,t)).join('')+'</div>';
 else if(App.prefs.view==='list')host.innerHTML='<div class="list-view">'+visible.map(e=>`<article class="list-row"><div class="date-label">${esc(eventLabel(e,t))}</div><div class="list-content"><h3><button class="table-title" data-open-event="${esc(e.id)}">${esc(e.title)}</button></h3><p>${esc(e.summary)}</p>${App.prefs.density==='full'?`<div class="markdown">${markdown(e.markdown)}</div>`:''}<div class="event-meta">${relationsHTML(e,t)}</div></div></article>`).join('')+'</div>';
 else if(App.prefs.view==='table')renderTable(host,visible,t);
 else if(App.prefs.view==='relations')renderRelationsView(host,events,t);else renderScale(host,events,t);
 if(!['horizontal','relations'].includes(App.prefs.view)&&events.length>pageSize)host.insertAdjacentHTML('beforeend',`<div class="pagination"><button class="btn" data-page="${page-1}" ${page===0?'disabled':''}>Précédent</button><span>${page+1} / ${Math.ceil(events.length/pageSize)} · ${events.length} repères</span><button class="btn" data-page="${page+1}" ${(page+1)*pageSize>=events.length?'disabled':''}>Suivant</button></div>`);
}
const TABLE_COLUMNS={place:'Lieu',tags:'Tags',edtf:'Date normalisée (EDTF)',sources:'Sources'};
function renderTable(host,events,t){
 const columns=new Set(App.prefs.columns.split(',').filter(key=>Object.hasOwn(TABLE_COLUMNS,key)));
 const optional=Object.entries(TABLE_COLUMNS).map(([key,label])=>`<label><input type="checkbox" data-column="${key}" ${columns.has(key)?'checked':''}> ${label}</label>`).join('');
 host.innerHTML=`<div class="bulk-tools"><label>Tri <select data-table-sort><option value="time">Date</option><option value="title">Titre</option></select></label><details class="column-menu"><summary>Colonnes</summary><div>${optional}</div></details><button class="btn" data-bulk="select">Sélectionner la page</button>${App.clusterFilter?'<button class="btn" data-clear-cluster>Quitter le regroupement</button>':''}</div><div class="bulk-tools" id="selectionTools" ${App.selected.size?'':'hidden'}><span id="selectionCount">${App.selected.size} sélectionné(s)</span><button class="btn" data-bulk="clear">Désélectionner</button><label>Fil <select id="bulkLane"><option value="">Sans fil</option>${t.lanes.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('')}</select></label><button class="btn" data-bulk="lane">Déplacer</button><input id="bulkTags" placeholder="Tags séparés par virgules" aria-label="Tags à modifier"><button class="btn" data-bulk="tagsAdd">Ajouter tags</button><button class="btn" data-bulk="tagsRemove">Retirer tags</button><button class="btn" data-bulk="duplicate">Dupliquer</button><button class="btn danger" data-bulk="delete">Supprimer</button></div><div class="table-wrap"><table class="table-view"><thead><tr><th>Choix</th><th>Date</th><th>Titre (modifiable)</th><th>Fil</th><th>Forme</th>${columns.has('place')?'<th>Lieu</th>':''}${columns.has('tags')?'<th>Tags</th>':''}${columns.has('edtf')?'<th>EDTF</th>':''}${columns.has('sources')?'<th>Sources</th>':''}</tr></thead><tbody>${events.map(e=>`<tr><td><input type="checkbox" data-select="${esc(e.id)}" aria-label="Sélectionner ${esc(e.title)}" ${App.selected.has(e.id)?'checked':''}></td><td><button class="table-title" data-open-event="${esc(e.id)}">${esc(eventLabel(e,t))}</button></td><td><input class="inline-title" data-edit="title" data-event="${esc(e.id)}" value="${esc(e.title)}" aria-label="Titre de ${esc(e.title)}"></td><td>${esc(eventLane(e,t))}</td><td>${e.temporal.kind==='interval'?'Période':'Repère'}</td>${columns.has('place')?`<td><input data-edit="place" data-event="${esc(e.id)}" value="${esc(e.place)}" aria-label="Lieu de ${esc(e.title)}"></td>`:''}${columns.has('tags')?`<td><input data-edit="tags" data-event="${esc(e.id)}" value="${esc(e.tags.join(', '))}" aria-label="Tags de ${esc(e.title)}"></td>`:''}${columns.has('edtf')?`<td>${esc(T.edtf(e.temporal,system(t)))}</td>`:''}${columns.has('sources')?`<td>${esc(e.sourceIds.map(id=>projectIndex().sources.get(id)?.title||'').filter(Boolean).join(', '))}</td>`:''}</tr>`).join('')}</tbody></table></div>`;
 host.querySelector('[data-table-sort]').value=App.prefs.sort;
}
function updateSelectionTools(){const tools=$('#selectionTools');if(tools){tools.hidden=!App.selected.size;$('#selectionCount').textContent=App.selected.size+' sélectionné(s)';}}
function bulk(action){if(!['select','clear'].includes(action)&&!guardCompatible())return;const t=currentTimeline(),ids=new Set(App.selected);if(action==='select'){const rows=$$('[data-select]');rows.forEach(el=>{App.selected.add(el.dataset.select);el.checked=true});updateSelectionTools();return;}if(action==='clear'){App.selected.clear();render();return;}if(!ids.size){toast('Sélectionne au moins un repère.');return;}const lane=$('#bulkLane').value||null,tags=$('#bulkTags').value.split(',').map(x=>x.trim()).filter(Boolean);if(action==='delete'&&!confirm('Supprimer '+ids.size+' repères ? L’action peut être annulée.'))return;commit(p=>{if(action==='delete'){Object.assign(p,P.removeEvents(p,t.id,[...ids]));return;}const target=p.timelines.find(x=>x.id===t.id);for(const e of target.events.filter(e=>ids.has(e.id))){if(action==='lane')e.laneId=lane;else if(action==='tagsAdd')e.tags=[...new Set([...e.tags,...tags])];else if(action==='tagsRemove')e.tags=e.tags.filter(x=>!tags.includes(x));else if(action==='duplicate'){const copy=P.clone(e);copy.id=P.id();copy.title+=' — copie';copy.externalIds={};copy.createdAt=copy.updatedAt=P.stamp();target.events.push(copy);}e.updatedAt=P.stamp();}},'Modification groupée appliquée.');}
function renderScale(host,events,t){const full=bounds(t),domain=getScaleCamera(),s=system(t);host.innerHTML='<p class="notice">Distances proportionnelles. Molette : zoom au curseur ; glisser : déplacement. Les regroupements ouvrent les données exactes.</p><div class="scale-wrap">'+ChroneaScale.svg(events,t,s,domain,{width:Math.max(800,Math.min(1500,$('#canvas').clientWidth-60))})+'</div>';const bins=Array(80).fill(0);for(const e of t.events){const r=eventRange(e,t);if(r.anchor!==null)bins[Math.min(79,Math.max(0,Math.floor((r.anchor-full.min)/(full.max-full.min)*80)))]++}const max=Math.max(1,...bins),x=n=>10+(n-full.min)/(full.max-full.min)*980;host.insertAdjacentHTML('beforeend',`<svg class="scale-overview" viewBox="0 0 1000 66" role="img" aria-label="Vue globale, cliquer pour déplacer la fenêtre">${bins.map((n,i)=>`<rect x="${10+i*12.25}" y="${48-n/max*35}" width="9" height="${n/max*35}" fill="#92aea0"/>`).join('')}<rect x="${Math.max(0,x(domain.min))}" y="8" width="${Math.max(2,Math.min(1000,x(domain.max))-Math.max(0,x(domain.min)))}" height="44" fill="#426b7a" fill-opacity=".12" stroke="#426b7a"/><text x="10" y="64" font-size="11">Vue globale · ${esc(coordinateLabel(full.min))} → ${esc(coordinateLabel(full.max))}</text></svg>`);const plot=host.querySelector('.scale-wrap');plot.addEventListener('wheel',event=>{event.preventDefault();const rect=plot.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));zoomAt(Math.exp(-event.deltaY*.002),ratio);},{passive:false});bindScaleGestures(plot,domain);host.querySelector('.scale-overview').addEventListener('click',event=>{const rect=event.currentTarget.getBoundingClientRect(),center=full.min+(event.clientX-rect.left)/rect.width*(full.max-full.min),half=(domain.max-domain.min)/2;setScaleCamera({min:center-half,max:center+half});});}
// Glisser et pincer passent par la même caméra. Le SVG donne un aperçu, puis la caméra est validée au relâchement.
function bindScaleGestures(plot,domain){const points=new Map(),svg=plot.querySelector('svg');let gesture=null;
 const relative=x=>Math.max(0,Math.min(1,(x-plot.getBoundingClientRect().left)/plot.getBoundingClientRect().width));
 const begin=()=>{const values=[...points.values()];gesture={camera:{...domain},start:values.map(p=>({...p})),pinch:values.length===2};svg.style.transform='';};
 plot.addEventListener('pointerdown',event=>{if(event.target.closest('[role="button"]'))return;points.set(event.pointerId,{x:event.clientX,y:event.clientY});try{plot.setPointerCapture(event.pointerId);}catch{}if(points.size<=2)begin();});
 plot.addEventListener('pointermove',event=>{if(!points.has(event.pointerId)||!gesture)return;points.set(event.pointerId,{x:event.clientX,y:event.clientY});const values=[...points.values()];if(values.length===2&&gesture.pinch){const start=gesture.start,initial=Math.hypot(start[1].x-start[0].x,start[1].y-start[0].y),current=Math.hypot(values[1].x-values[0].x,values[1].y-values[0].y),factor=Math.max(.01,current/Math.max(1,initial)),origin=(start[0].x+start[1].x)/2;svg.style.transformOrigin=(relative(origin)*100)+'% center';svg.style.transform='scaleX('+factor+')';}else if(values.length===1&&!gesture.pinch)svg.style.transform='translateX('+(values[0].x-gesture.start[0].x)+'px)';});
 const end=event=>{if(!points.has(event.pointerId))return;points.set(event.pointerId,{x:event.clientX,y:event.clientY});const values=[...points.values()],rect=plot.getBoundingClientRect();svg.style.transform='';if(gesture?.pinch&&values.length===2){const start=gesture.start,initial=Math.hypot(start[1].x-start[0].x,start[1].y-start[0].y),current=Math.hypot(values[1].x-values[0].x,values[1].y-values[0].y),factor=current/Math.max(1,initial),initialCenter=(start[0].x+start[1].x)/2,currentCenter=(values[0].x+values[1].x)/2,span=(gesture.camera.max-gesture.camera.min)/Math.max(.01,factor),anchor=gesture.camera.min+(gesture.camera.max-gesture.camera.min)*relative(initialCenter),ratio=relative(currentCenter);points.clear();gesture=null;setScaleCamera({min:anchor-span*ratio,max:anchor+span*(1-ratio)});return;}
 if(gesture&&!gesture.pinch&&values.length===1){const dx=values[0].x-gesture.start[0].x;if(Math.abs(dx)>5){const delta=dx/rect.width*(gesture.camera.max-gesture.camera.min);points.clear();gesture=null;setScaleCamera({min:domain.min-delta,max:domain.max-delta});return;}}
 points.delete(event.pointerId);if(!points.size)gesture=null;};
 plot.addEventListener('pointerup',end);plot.addEventListener('pointercancel',event=>{points.delete(event.pointerId);svg.style.transform='';gesture=null;});
}
// Une caméra graphique unique ; les filtres ne modifient jamais cette fenêtre.
function getFullDomain(){return bounds();}
function getScaleCamera(){return App.prefs.scaleCamera||getFullDomain();}
function getScaleZoomRatio(){const full=getFullDomain(),d=getScaleCamera();return (full.max-full.min)/(d.max-d.min);}
function syncScaleControls(){const ratio=getScaleZoomRatio(),value=Math.log2(ratio);$('#zoomInput').min=Math.min(-4,Math.floor(value));$('#zoomInput').max=Math.max(12,Math.ceil(value));$('#zoomInput').value=value;$('#zoomRatio').textContent='×'+Number(ratio.toPrecision(3)).toLocaleString('fr-FR');$('.zoom').hidden=App.prefs.view!=='horizontal';}
function setScaleCamera(camera){if(camera&&(!Number.isFinite(camera.min)||!Number.isFinite(camera.max)||camera.min>=camera.max)){toast('La fenêtre graphique doit avoir deux bornes ordonnées.');return false;}App.prefs.scaleCamera=camera?{...camera}:null;savePrefs();render();return true;}
function resetScaleCamera(){return setScaleCamera(null);}
function zoomScaleAt(factor,ratio=.5){const d=getScaleCamera(),anchor=d.min+(d.max-d.min)*ratio,span=Math.max(1e-8,(d.max-d.min)/factor);return setScaleCamera({min:anchor-span*ratio,max:anchor+span*(1-ratio)});}
function panScale(direction){const d=getScaleCamera(),step=(d.max-d.min)*.5*direction;return setScaleCamera({min:d.min+step,max:d.max+step});}
const zoomAt=zoomScaleAt;
function renderRelationsView(host,events,t){const visible=new Set(events.map(e=>e.id)),types=[...new Set(t.relations.map(r=>r.type))];let relations=t.relations.filter(r=>visible.has(r.sourceId)&&visible.has(r.targetId)&&(!App.prefs.relationType||r.type===App.prefs.relationType));const pageSize=150,page=App.prefs.page,start=page*pageSize,byId=new Map(t.events.map(e=>[e.id,e]));const graph=ChroneaGraph.svg(relations,t.events);host.innerHTML=`<div class="bulk-tools"><label>Type <select data-relation-filter><option value="">Tous</option>${types.map(type=>`<option value="${esc(type)}" ${type===App.prefs.relationType?'selected':''}>${esc(ChroneaRelationLabels[type]||type)}</option>`).join('')}</select></label><button class="btn" data-new-relation>Créer une relation</button><span>${relations.length} relation(s)</span></div><p class="notice">Graphe : ${graph.nodes} repères, ${graph.edges} liens. La liste ci-dessous donne accès à toutes les relations ; recherche et type réduisent le voisinage.</p><div class="scale-wrap">${graph.text}</div>`+relations.slice(start,start+pageSize).map(r=>`<article class="relation-row"><button class="table-title" data-open-event="${esc(r.sourceId)}">${esc(byId.get(r.sourceId)?.title)}</button><span>${r.direction==='directed'?'→':'↔'} ${esc(ChroneaRelationLabels[r.type]||r.type)}</span><button class="table-title" data-open-event="${esc(r.targetId)}">${esc(byId.get(r.targetId)?.title)}</button><span>${esc(r.note)}</span><button class="btn" data-remove-relation="${esc(r.id)}">Retirer</button></article>`).join('')+(relations.length>pageSize?`<div class="pagination"><button class="btn" data-page="${page-1}" ${!page?'disabled':''}>Précédent</button>${page+1}/${Math.ceil(relations.length/pageSize)}<button class="btn" data-page="${page+1}" ${start+pageSize>=relations.length?'disabled':''}>Suivant</button></div>`:'')+(!relations.length?'<p class="notice">Les relations relient des repères sans modifier leurs dates. Crée une relation de causalité, dépendance, contradiction ou proximité.</p>':'');}
function relationDirection(type){return ['related','sameSubject','contradicts'].includes(type)?'undirected':'directed';}
function newRelation(sourceId=null){const t=currentTimeline();if(!guardCompatible())return;if(t.events.length<2){toast('Deux repères sont nécessaires. Enregistre d’abord le nouvel élément.');return;}const dialog=$('#relationDialog');$('#relationSource').innerHTML=$('#relationTarget').innerHTML=t.events.map(e=>`<option value="${esc(e.id)}">${esc(e.title)}</option>`).join('');$('#relationSource').value=sourceId||t.events[0].id;$('#relationTarget').value=t.events.find(e=>e.id!==$('#relationSource').value).id;$('#relationType').value='related';$('#relationNote').value='';dialog.showModal();}
function renderRelations(e){const t=currentTimeline(),byId=new Map(t.events.map(x=>[x.id,x]));$('#relationList').innerHTML=e?t.relations.filter(r=>r.sourceId===e.id||r.targetId===e.id).map(r=>{const other=byId.get(r.sourceId===e.id?r.targetId:r.sourceId),arrow=r.direction==='undirected'?'↔':r.sourceId===e.id?'→':'←';return `<div class="relation-row"><span>${arrow} ${esc(ChroneaRelationLabels[r.type]||r.type)} · ${esc(other?.title||'')}</span><button type="button" class="btn" data-remove-event-relation="${esc(r.id)}" aria-label="Retirer la relation avec ${esc(other?.title||'')}">Retirer</button></div>`;}).join(''):'<p class="notice">Enregistre ce repère avant de créer des relations.</p>';$('#newEventRelation').disabled=!e||t.events.length<2;}
function savePrefs(){try{localStorage.setItem('chronea.preferences.v3',JSON.stringify({...App.prefs,currentId:App.currentId,projectId:App.project.id}));}catch{/* L'export demeure disponible. */}}
function recordHistory(){App.history.push({project:App.project,assets:new Map(App.assets)});App.future=[];let bytes=0;App.history=App.history.slice(-30).reverse().filter(row=>(bytes+=JSON.stringify(row.project).length)<16*1024*1024).reverse();}
function commit(mutator,message,options={}){try{const draft=P.clone(App.project),assets=new Map(App.assets);mutator(draft,assets);if(draft.id===App.project.id&&isMixedProject(App.project))throw Error('Projet mixte en lecture : sépare-le depuis Projet avant de le modifier.');draft.updatedAt=P.stamp();P.validate(draft);recordHistory();if(draft.id!==App.project.id){App.fileHandle=null;App.lastFileSave=null;}App.project=draft;App.assets=assets;App.revision++;App.rangeCache=new WeakMap();if(options.clearSelection!==false)App.selected.clear();persist();if(options.render!==false)render();else{$('#undoBtn').disabled=false;$('#redoBtn').disabled=true;}if(message)toast(message);return true;}catch(error){toast(error.message);return false;}}
function persist(){status(App.blocked?I18N.fr.recovery:I18N.fr.modified);clearTimeout(App.saveTimer);if(!App.blocked)App.saveTimer=setTimeout(flushSave,450);}
function flushSave(){
 clearTimeout(App.saveTimer);App.saveTimer=null;if(App.blocked)return Promise.resolve(false);
 const revision=App.revision,project=P.clone(App.project),assets=new Map(App.assets);
 App.saveQueue=App.saveQueue.catch(()=>{}).then(async()=>{try{const backend=await App.store.save(project,assets,{validated:true});App.savedRevision=revision;savePrefs();status(App.revision===revision?I18N.fr.saved+' ('+backend+') à '+new Date().toLocaleTimeString('fr-FR'):I18N.fr.modified);return true;}catch(error){status(I18N.fr.unavailable);toast(error.message||I18N.fr.unavailable);return false;}});return App.saveQueue;
}
function undo(redo=false){const source=redo?App.future:App.history,destination=redo?App.history:App.future;if(!source.length)return;destination.push({project:App.project,assets:new Map(App.assets)});const row=source.pop();if(row.project.id!==App.project.id){App.fileHandle=null;App.lastFileSave=null;App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.group='';App.prefs.search='';App.prefs.page=0;App.clusterFilter=null;}App.project=row.project;App.assets=row.assets;App.currentId=App.project.timelines.some(t=>t.id===App.currentId)?App.currentId:App.project.timelines[0].id;App.rangeCache=new WeakMap();App.revision++;persist();render();toast(redo?'Action rétablie.':'Action annulée.');}
function monthOptions(selector){$(selector).innerHTML='<option value="">Mois…</option>'+['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'].map((name,i)=>`<option value="${i+1}">${name}</option>`).join('');}
function openEditor(eventId=null){
 App.returnFocus=document.activeElement;App.editorSession++;App.editingId=eventId;const t=currentTimeline(),e=t.events.find(e=>e.id===eventId),s=system(t),a=e?.temporal.start||e?.temporal.end,b=e?.temporal.end&&e?.temporal.start?e.temporal.end:null;
 $('#drawerTitle').textContent=e?(e.temporal.kind==='interval'?'Modifier une période':'Modifier un repère'):'Nouveau repère';$('#deleteEventBtn').classList.toggle('hidden',!e);
 for(const [field,value]of Object.entries({eventTitle:e?.title,eventColor:e?.color||'#925b39',eventTags:e?.tags.join(', '),eventLocation:e?.place,eventSummary:e?.summary,eventMarkdown:e?.markdown,eventLinks:e?.links,eventSources:e?.metadata?.provenanceNote||'',dateLabel:e?.displayDate}))$('#'+field).value=value||'';

 App.temporalEditor=new ChroneaTemporalEditor.Editor($('#temporalEditor'),s,e?.temporal,{shape:b?'interval':'point'});setFormShape(b?'interval':'point');
 $('#timeSystemNotice').textContent=s.type==='numeric'?'Axe numérique · '+s.definition.unit:s.type==='customCalendar'?'Calendrier du projet · '+s.name:'L’année suffit. Le mois et le jour sont facultatifs.';
 App.pendingLanes=P.clone(t.lanes).sort((a,b)=>a.order-b.order);renderEventLanes(e?.laneId||'');
 App.pendingSources=e?e.sourceIds.map(id=>P.clone(projectIndex().sources.get(id))):[];renderSources();
 App.pendingMedia=e?eventMedia(e).map(m=>({media:P.clone(m),blob:App.assets.get(m.storageRef)})):[];renderAttachments(false);renderRelations(e);
 $('#eventDrawer').inert=false;$('.app').inert=true;$('#addEventBtn').inert=true;$('#eventDrawer').classList.add('open');$('#drawerBackdrop').classList.add('open');$('#eventDrawer').setAttribute('aria-hidden','false');setTimeout(()=>{if($('#eventDrawer').classList.contains('open'))$('#eventTitle').focus();},40);
}
function closeEditor(){App.editorSession++;App.editingId=null;App.pendingMedia=[];$('#eventDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('open');$('#eventDrawer').setAttribute('aria-hidden','true');$('#eventDrawer').inert=true;$('.app').inert=false;$('#addEventBtn').inert=false;if(App.returnFocus?.isConnected)App.returnFocus.focus();else $('#addEventBtn').focus();}
function captureAttachments(){for(const [i,row]of App.pendingMedia.entries()){const alt=$(`[data-media-alt="${i}"]`),caption=$(`[data-media-caption="${i}"]`);if(alt)row.media.alt=alt.value;if(caption)row.media.caption=caption.value;}}
function renderAttachments(sync=true){if(sync)captureAttachments();$('#attachmentList').innerHTML=App.pendingMedia.map((row,i)=>`<div class="attachment"><span class="name">${esc(row.media.name)} (${Math.round(row.media.size/1024)} Ko)</span><button type="button" data-remove-media="${i}" aria-label="Retirer ${esc(row.media.name)}">×</button></div><label class="field">Texte alternatif<input data-media-alt="${i}" value="${esc(row.media.alt||'')}"></label><label class="field">Légende<input data-media-caption="${i}" value="${esc(row.media.caption||'')}"></label>`).join('');}
function renderEventLanes(selected=''){$('#eventGroup').innerHTML='<option value="">Aucun fil</option>'+App.pendingLanes.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}${l.visible?'':' (masqué)'}</option>`).join('')+'<option value="__new">+ Créer un fil</option>';$('#eventGroup').value=selected;}
function openLanes(){App.editingLanes=P.clone(currentTimeline().lanes).sort((a,b)=>a.order-b.order);renderLaneRows();$('#lanesDialog').showModal();}
function captureLaneRows(){for(const [i,row]of App.editingLanes.entries())for(const el of $('#laneRows').querySelectorAll('[data-lane-index="'+i+'"][data-lane-field]'))row[el.dataset.laneField]=el.type==='checkbox'?el.checked:el.value;}
function renderLaneRows(){$('#laneRows').innerHTML=App.editingLanes.map((l,i)=>`<div class="lane-editor-row"><label>Nom<input data-lane-index="${i}" data-lane-field="name" value="${esc(l.name)}"></label><label>Couleur<input type="color" data-lane-index="${i}" data-lane-field="color" value="${esc(l.color||'#8fae9a')}"></label><label><input type="checkbox" data-lane-index="${i}" data-lane-field="visible" ${l.visible?'checked':''}> Visible</label><button class="icon-btn" data-lane-move="${i}" data-lane-step="-1" aria-label="Monter ${esc(l.name)}" ${i===0?'disabled':''}>↑</button><button class="icon-btn" data-lane-move="${i}" data-lane-step="1" aria-label="Descendre ${esc(l.name)}" ${i===App.editingLanes.length-1?'disabled':''}>↓</button></div>`).join('');}
function validateLaneNames(list){const names=list.map(l=>l.name.trim().toLocaleLowerCase('fr'));if(names.some(n=>!n)||new Set(names).size!==names.length)throw Error('Chaque fil doit avoir un nom distinct et renseigné.');}
function saveLanes(){if(!guardCompatible())return;try{captureLaneRows();validateLaneNames(App.editingLanes);const rows=App.editingLanes.map((l,i)=>({...l,name:l.name.trim(),order:i}));if(commit(p=>p.timelines.find(t=>t.id===App.currentId).lanes=rows,'Fils mis à jour.'))$('#lanesDialog').close();}catch(error){toast(error.message);}}
function openNewLane(context='event'){App.newLaneContext=context;$('#newLaneName').value='';$('#newLaneColor').value='#8fae9a';$('#newLaneDialog').showModal();}
function saveNewLane(){try{const list=App.newLaneContext==='event'?App.pendingLanes:App.editingLanes,l={id:P.id(),name:$('#newLaneName').value.trim(),color:$('#newLaneColor').value,visible:true,order:list.length,description:''};validateLaneNames([...list,l]);list.push(l);if(App.newLaneContext==='event')renderEventLanes(l.id);else renderLaneRows();$('#newLaneDialog').close();return true;}catch(error){toast(error.message);return false;}}
function renderSources(){$('#sourceList').innerHTML=App.pendingSources.map(s=>`<div class="source-row"><span>${esc(s.title)}</span><button type="button" class="btn" data-edit-source="${esc(s.id)}">Modifier</button><button type="button" class="btn" data-unlink-source="${esc(s.id)}">Détacher</button></div>`).join('')||'<p class="notice">Ajoute une archive, une référence ou un témoignage.</p>';}
function openSource(id=null){const source=App.pendingSources.find(s=>s.id===id);App.editingSourceId=id;for(const key of ['Title','Type','Citation','Url','Note'])$('#source'+key).value=source?.[key.toLowerCase()]||'';$('#sourceType').value=source?.type||'note';$('#sourceSharing').textContent=source?'Une source peut être partagée. Sa modification sera conservée pour tous les éléments qui la référencent.':'Cette nouvelle source sera ajoutée à cet élément.';$('#sourceDialog').showModal();}
function saveSource(){const title=$('#sourceTitle').value.trim(),url=$('#sourceUrl').value.trim();if(!title){toast('Ajoute un titre à la source.');$('#sourceTitle').focus();return false;}if(url&&!C.safeUrl(url)){toast('L’adresse de la source doit être un lien sûr.');return false;}const old=App.pendingSources.find(s=>s.id===App.editingSourceId),source={...(old||{}),id:old?.id||P.id(),title,type:$('#sourceType').value.trim()||'note',citation:$('#sourceCitation').value.trim(),url,note:$('#sourceNote').value.trim()};if(old)Object.assign(old,source);else App.pendingSources.push(source);renderSources();$('#sourceDialog').close();return true;}
async function handleFiles(files){
 const session=App.editorSession;App.fileReads++;$('#saveEventBtn').disabled=true;
 try{const added=[];for(const file of files){try{if(file.size>S.MAX_MEDIA)throw new Error('20 Mo maximum par fichier.');const type=file.type||'application/octet-stream',blob=new Blob([await file.arrayBuffer()],{type});C.validateMedia({type,size:blob.size,dataUrl:await S.dataURL(blob)},S.MAX_MEDIA);const checksum=await S.checksum(blob),existing=App.project.media.find(m=>m.checksum===checksum&&m.mimeType===type);const mid=existing?.id||P.id();const media=existing?P.clone(existing):{id:mid,name:file.name,mimeType:type,size:blob.size,storageRef:'media/'+mid,checksum,alt:'',caption:''};if(existing&&existing.name!==file.name)media.metadata={...(media.metadata||{}),aliases:[...new Set([...(media.metadata?.aliases||[]),file.name])]};added.push({media,blob});}catch(error){toast(file.name+' : '+error.message);}}
 if(session===App.editorSession&&$('#eventDrawer').classList.contains('open')){for(const row of added)if(!App.pendingMedia.some(x=>x.media.id===row.media.id))App.pendingMedia.push(row);renderAttachments();}
 }finally{App.fileReads--;$('#saveEventBtn').disabled=App.fileReads>0;}
}
function formShape(){return $('[name=elementShape]:checked').value;}
function setFormShape(kind){$('[name=elementShape][value='+kind+']').checked=true;App.temporalEditor?.setShape(kind);$('#drawerTitle').textContent=App.editingId?(kind==='interval'?'Modifier une période':'Modifier un repère'):(kind==='interval'?'Nouvelle période':'Nouveau repère');}
function formTemporal(){return App.temporalEditor.read();}
function saveEvent(){
 if(!guardCompatible())return;
 if(App.fileReads){toast('Lecture des fichiers en cours.');return;}
 const title=$('#eventTitle').value.trim();if(!title){$('#eventTitle').focus();toast('Ajoute un titre.');return;}
 const t=currentTimeline(),old=t.events.find(e=>e.id===App.editingId);let temporal;
 try{temporal=formTemporal();T.validateTemporal(temporal,system());C.validateLinks($('#eventLinks').value.trim());if(!temporal.start&&!temporal.end&&!$('#dateLabel').value.trim())throw new Error('Indique un repère ou un libellé temporel.');
 }catch(error){toast(error.message);return;}
 const eid=old?.id||P.id();
 const ok=commit((draft,assets)=>{
  const timeline=draft.timelines.find(x=>x.id===t.id),e=old?timeline.events.find(x=>x.id===eid):P.event(title,temporal);e.id=eid;if(old?.type)e.metadata={...(e.metadata||{}),legacyType:e.metadata?.legacyType??old.type};
  Object.assign(e,{title,temporal,summary:$('#eventSummary').value.trim(),markdown:$('#eventMarkdown').value.trim(),links:$('#eventLinks').value.trim(),displayDate:$('#dateLabel').value.trim(),color:$('#eventColor').value,tags:$('#eventTags').value.split(',').map(v=>v.trim()).filter(Boolean),place:$('#eventLocation').value.trim(),updatedAt:P.stamp()});
  timeline.lanes=P.clone(App.pendingLanes);e.laneId=$('#eventGroup').value||null;if(e.laneId&&!timeline.lanes.some(l=>l.id===e.laneId))throw Error('Choisis un fil existant.');
  e.metadata={...(e.metadata||{}),provenanceNote:$('#eventSources').value.trim()};e.sourceIds=App.pendingSources.map(source=>{const existing=draft.sources.find(s=>s.id===source.id);if(existing)Object.assign(existing,P.clone(source));else draft.sources.push(P.clone(source));return source.id;});
  e.mediaIds=App.pendingMedia.map((row,i)=>{row.media.alt=$(`[data-media-alt="${i}"]`)?.value||row.media.alt||'';row.media.caption=$(`[data-media-caption="${i}"]`)?.value||row.media.caption||'';const index=draft.media.findIndex(m=>m.id===row.media.id);if(index>=0)draft.media[index]=P.clone(row.media);else draft.media.push(P.clone(row.media));if(row.blob)assets.set(row.media.storageRef,row.blob);return row.media.id;});
  if(!old)timeline.events.push(e);
 },old?'Événement mis à jour.':'Événement ajouté.');if(ok){closeEditor();render();$('#addEventBtn').focus();}
}
function deleteEvent(){const t=currentTimeline(),e=t.events.find(e=>e.id===App.editingId);if(!e||!confirm('Supprimer « '+e.title+' » ?'))return;const next=P.removeEvents(App.project,t.id,[e.id]);if(commit(draft=>Object.assign(draft,next),'Événement supprimé.')){closeEditor();render();}}
function projectSystemIds(project=App.project){return [...new Set(project.timelines.map(t=>t.timeSystemId))];}
function isMixedProject(project=App.project){return projectSystemIds(project).length>1;}
function projectSystem(){return App.project.timeSystems.find(s=>s.id===projectSystemIds()[0]);}
function guardCompatible(){if(isMixedProject()){toast('Ce projet est en lecture. Sépare ses chronologies depuis Projet pour les modifier.');return false;}return true;}
function openTimelineDialog(){const t=currentTimeline();$('#timelineName').value=t.title;$('#timelineSystemLabel').textContent='Temporalité héritée du projet : '+system().name;renderSpanRows();$('#timelineDialog').showModal();}
function saveTimelineSettings(){if(!guardCompatible())return;if(commit(p=>p.timelines.find(t=>t.id===App.currentId).title=$('#timelineName').value.trim()||'Sans titre','Chronologie renommée.'))$('#timelineDialog').close();}
function defaultSystem(type){return {id:P.id(),type,name:type==='gregorian'?'Calendrier grégorien':type==='numeric'?'Axe imaginaire':'Calendrier imaginaire',definition:type==='customCalendar'?{months:[{name:'Aube',days:30},{name:'Clair',days:30}],intercalaryDays:0,eras:[{name:'Fondation',offset:0}],displayFormat:'jour mois année ère'}:type==='numeric'?{unit:'cycle',direction:1}:{}};}
function selectedProjectSystem(){const mode=$('#projectTimeMode').value,type=mode==='universal'?'numeric':mode==='custom'?'customCalendar':'gregorian',old=projectSystem();const definition=type==='gregorian'?{}:readSystemDefinition(type,old?.type===type?old.definition:{});const s={id:old?.id||P.id(),type,name:$('#systemName').value.trim()||'Temporalité du projet',definition};T.validateSystem(s);return s;}
function projectTimePreview(){const old=projectSystem(),mode=$('#projectTimeMode').value,type=mode==='universal'?'numeric':mode==='custom'?'customCalendar':'gregorian',dated=App.project.timelines.flatMap(t=>[...t.events,...t.spans]).filter(e=>e.temporal.start||e.temporal.end).length;$('#projectTimePreview').textContent=dated+' éléments datés dans '+App.project.timelines.length+' chronologie(s). '+(type!==old?.type&&dated?'La conversion vers une autre famille est indisponible sans correspondance définie. Le projet original reste intact.':'Les composants des dates sont conservés ; le nouveau calendrier sera validé avant application.');$('#projectTimeApply').disabled=isMixedProject()||type!==old?.type&&dated>0;}
function openProjectTime(){const s=projectSystem();$('#projectTimeMode').value=s.type==='numeric'?'universal':s.type==='customCalendar'?'custom':'calendar';$('#systemName').value=s.name;fillSystemDefinition(s);projectTimePreview();$('#projectTimeDialog').showModal();}
function saveProjectTime(){if(!guardCompatible())return;try{const old=projectSystem(),next=selectedProjectSystem(),dated=App.project.timelines.some(t=>[...t.events,...t.spans].some(e=>e.temporal.start||e.temporal.end));if(next.type!==old.type&&dated)throw Error('Conversion non définie : aucune date ne sera effacée. Crée un nouveau projet dans cette temporalité.');const candidate=P.clone(App.project);remapCalendarDates(candidate,old,next);Object.assign(candidate.timeSystems.find(s=>s.id===old.id),next);P.validate(candidate);if(dated&&JSON.stringify(next.definition)!==JSON.stringify(old.definition)&&!confirm('Appliquer cette définition à toutes les chronologies ? Les mois et ères utilisés sont conservés ; leur position sur l’Échelle peut changer. Enregistre une copie fichier avant de continuer.'))return;if(commit(p=>Object.assign(p,candidate),'Temporalité du projet appliquée.')){App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;$('#projectTimeDialog').close();render();}}catch(error){toast(error.message);}}
async function createNewProject(next=defaultSystem('gregorian')){if(!await flushSave()){toast('Enregistre une copie fichier avant de changer de projet.');return false;}const p=P.create('Nouveau projet');p.timeSystems=[{...P.clone(next),id:P.id()}];p.timelines[0].timeSystemId=p.timeSystems[0].id;P.validate(p);recordHistory();revokeURLs();App.project=p;App.assets=new Map();App.currentId=p.timelines[0].id;App.fileHandle=null;App.lastFileSave=null;App.revision++;App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.search='';App.prefs.group='';App.prefs.page=0;App.clusterFilter=null;persist();render();return true;}
function splitProjectBySystem(project,assets){return projectSystemIds(project).map(sid=>{const p=P.clone(project);p.timelines=p.timelines.filter(t=>t.timeSystemId===sid);p.timeSystems=p.timeSystems.filter(s=>s.id===sid);const usedSources=new Set(p.timelines.flatMap(t=>t.events.flatMap(e=>e.sourceIds))),usedMedia=new Set(p.timelines.flatMap(t=>t.events.flatMap(e=>e.mediaIds)));p.sources=p.sources.filter(s=>usedSources.has(s.id));p.media=p.media.filter(m=>usedMedia.has(m.id));p.title+=' — '+p.timeSystems[0].name;const result=D.rebase(p,assets);result.project.metadata={...result.project.metadata,splitFrom:project.id};return result;});}
async function splitMixedProject(){try{if(!isMixedProject())return;if(!await flushSave())throw Error('Enregistre le projet original dans un fichier avant de le séparer.');if(!App.store.db)throw Error('La séparation en plusieurs projets nécessite le cache IndexedDB. Exporte chaque chronologie en JSON pour les ouvrir séparément.');const parts=splitProjectBySystem(App.project,App.assets);for(const part of parts)await App.store.save(part.project,part.assets);recordHistory();App.project=parts[0].project;App.assets=parts[0].assets;App.currentId=App.project.timelines[0].id;App.fileHandle=null;App.lastFileSave=null;App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.group='';App.prefs.search='';App.clusterFilter=null;App.revision++;persist();$('#projectDialog').close();render();toast(parts.length+' projets créés. L’original reste dans le cache.');}catch(error){toast(error.message);}}
function fillSystemDefinition(s){const d=s.definition;$('#timelineUnit').value=d.unit||'cycle';$('#timelineUnitField').classList.toggle('hidden',s.type!=='numeric');$('#numericDefinitionFields').classList.toggle('hidden',s.type!=='numeric');$('#calendarDefinitionFields').classList.toggle('hidden',s.type!=='customCalendar');$('#systemDirection').value=d.direction||1;App.calendarRows={months:(d.months||[]).map((row,i)=>({...P.clone(row),originalIndex:i+1})),eras:(d.eras||[]).map(row=>({...P.clone(row),originalName:row.name}))};renderCalendarRows();$('#calendarIntercalary').value=d.intercalaryDays||0;$('#calendarFormat').value=d.displayFormat||'jour mois année ère';}
function calendarHost(key){return $(key==='months'?'#calendarMonthRows':'#calendarEraRows');}
function captureCalendarRows(){for(const key of ['months','eras'])for(const [i,row]of App.calendarRows[key].entries())for(const el of calendarHost(key).querySelectorAll('[data-calendar-index="'+i+'"][data-row-field]'))row[el.dataset.rowField]=el.dataset.rowField==='name'?el.value.trim():Number(el.value);}
function renderCalendarRows(){for(const key of ['months','eras'])calendarHost(key).innerHTML=App.calendarRows[key].map((row,i)=>`<div class="calendar-editor-row"><label>Nom<input data-calendar-index="${i}" data-row-field="name" value="${esc(row.name)}"></label><label>${key==='months'?'Jours':'Décalage en années'}<input type="number" step="1" ${key==='months'?'min="1"':''} data-calendar-index="${i}" data-row-field="${key==='months'?'days':'offset'}" value="${row[key==='months'?'days':'offset']}"></label><button type="button" class="icon-btn" data-calendar-key="${key}" data-calendar-index="${i}" data-calendar-action="up" aria-label="Monter ${esc(row.name)}" ${i===0?'disabled':''}>↑</button><button type="button" class="icon-btn" data-calendar-key="${key}" data-calendar-index="${i}" data-calendar-action="down" aria-label="Descendre ${esc(row.name)}" ${i===App.calendarRows[key].length-1?'disabled':''}>↓</button><button type="button" class="btn" data-calendar-key="${key}" data-calendar-index="${i}" data-calendar-action="remove">Retirer</button></div>`).join('');}
function readSystemDefinition(type,previous){if(type==='numeric')return {...previous,unit:$('#timelineUnit').value.trim()||'cycle',direction:Number($('#systemDirection').value)};captureCalendarRows();const rows=key=>App.calendarRows[key].map(row=>{const copy={...row};delete copy.originalIndex;delete copy.originalName;return copy;});for(const key of ['months','eras']){const names=App.calendarRows[key].map(row=>row.name.toLocaleLowerCase('fr'));if(names.some(n=>!n)||new Set(names).size!==names.length)throw Error('Les noms des '+(key==='months'?'mois':'ères')+' doivent être renseignés et distincts.');}return {...previous,months:rows('months'),intercalaryDays:Number($('#calendarIntercalary').value),eras:rows('eras'),displayFormat:$('#calendarFormat').value};}
function remapCalendarDates(project,old,next){if(old.type!=='customCalendar'||next.type!=='customCalendar')return;const months=new Map(App.calendarRows.months.filter(row=>row.originalIndex).map((row,i)=>[row.originalIndex,App.calendarRows.months.indexOf(row)+1])),eras=new Map(App.calendarRows.eras.filter(row=>row.originalName).map(row=>[row.originalName,row.name]));for(const t of project.timelines)for(const e of [...t.events,...t.spans])for(const ep of [e.temporal.start,e.temporal.end])if(ep)for(const key of ['value','notBefore','notAfter']){const v=ep[key];if(!v||typeof v!=='object')continue;if(v.month!==undefined){if(v.month===old.definition.months.length+1&&old.definition.intercalaryDays){if(!next.definition.intercalaryDays)throw Error('Des dates utilisent les jours intercalaires. Leur suppression est refusée.');v.month=next.definition.months.length+1;}else{if(!months.has(v.month))throw Error('Des dates utilisent un mois retiré. Aucune date n’a été modifiée.');v.month=months.get(v.month);}}if(v.era){if(!eras.has(v.era))throw Error('Des dates utilisent une ère retirée. Aucune date n’a été modifiée.');v.era=eras.get(v.era);}}}
function renderSpanRows(){const t=currentTimeline();$('#spanRows').innerHTML=t.spans.map(s=>`<button class="btn" data-edit-span="${esc(s.id)}">${esc(s.title)} — ${esc(T.label(s.temporal,system()))}</button>`).join('');}
function openSpan(id=null){const t=currentTimeline(),s=t.spans.find(x=>x.id===id);App.editingSpanId=id;$('#spanTitle').value=s?.title||'';App.spanEditor=new ChroneaTemporalEditor.Editor($('#spanTemporalEditor'),system(),s?.temporal||{kind:'interval',start:null,end:null},{prefix:'phase',shape:'interval',allowOpen:true});$('#spanColor').value=s?.color||'#cadbc8';$('#spanLane').innerHTML='<option value="">Tous les fils</option>'+t.lanes.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');$('#spanLane').value=s?.laneId||'';$('#deleteSpanBtn').classList.toggle('hidden',!s);$('#spanDialog').showModal();}
function saveSpan(){if(!guardCompatible())return;try{const temporal=App.spanEditor.read();if(commit(p=>{const t=p.timelines.find(t=>t.id===App.currentId),old=t.spans.find(s=>s.id===App.editingSpanId);const value={id:old?.id||P.id(),title:$('#spanTitle').value.trim(),temporal,laneId:$('#spanLane').value||null,color:$('#spanColor').value};if(old)Object.assign(old,value);else t.spans.push(value);},'Ère / phase enregistrée.')){$('#spanDialog').close();renderSpanRows();}}catch(error){toast(error.message);}}
function newTimeline(){const title=prompt('Nom de la chronologie :','Nouvelle chronologie');if(!title)return;if(!guardCompatible())return;const t=P.timeline(title,projectSystem().id);if(!commit(p=>p.timelines.push(t)))return;App.currentId=t.id;App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.group='';$('#timelineDialog').close();render();}
function duplicateTimeline(){const original=currentTimeline(),t=P.clone(original),map=new Map();t.id=P.id();t.title+=' — copie';for(const obj of [...t.events,...t.lanes,...t.spans]){const fresh=P.id();map.set(obj.id,fresh);obj.id=fresh;}for(const e of [...t.events,...t.spans])if(e.laneId)e.laneId=map.get(e.laneId);for(const r of t.relations){r.id=P.id();r.sourceId=map.get(r.sourceId);r.targetId=map.get(r.targetId);}commit(p=>p.timelines.push(t),'Chronologie dupliquée.');App.currentId=t.id;$('#timelineDialog').close();render();}
function deleteTimeline(){const t=currentTimeline();if(App.project.timelines.length===1){toast('Garde au moins une chronologie.');return;}if(!confirm('Supprimer « '+t.title+' » ?'))return;commit(p=>p.timelines=p.timelines.filter(x=>x.id!==t.id),'Chronologie supprimée.');App.currentId=App.project.timelines[0].id;$('#timelineDialog').close();render();}
function loadDemo(){if(!guardCompatible())return;if(projectSystem().type!=='gregorian'){toast('L’exemple utilise le temps réel. Crée un projet réel pour l’ouvrir.');return;}const t=currentTimeline();if(t.events.length&&!confirm('Remplacer les événements par l’exemple ?'))return;commit(p=>{const target=p.timelines.find(x=>x.id===t.id);target.title='Fragments d’un voyage — exemple';target.events=[['La cabane au bord du lac',2012,7,'Un été de lumière sur l’eau.','approximate'],['Première traversée',2016,4,'Le voyage devient concret.','exact'],['Les années du carnet rouge',2018,1,'Conserver les traces.','exact'],['Retour vers la vallée',2023,10,'Le paysage est le même, le regard change.','exact']].map(([title,year,month,summary,qualifier])=>{const e=P.event(title,{kind:'point',start:{value:{year,month},precision:'month',qualifier},end:null});e.type='Souvenir';e.summary=summary;return e;});target.events[2].temporal.kind='interval';target.events[2].temporal.end={value:{year:2020,month:9},precision:'month',qualifier:'exact'};target.events[2].markdown='## Ce qui change\n\n- écrire davantage\n- conserver les traces';target.relations=target.events.slice(1).map((e,i)=>({id:P.id(),sourceId:target.events[i].id,targetId:e.id,type:'related',direction:'undirected',note:''}));target.lanes=[];target.spans=[];},'Exemple chargé.');App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.search='';if($('#timelineDialog').open)$('#timelineDialog').close();render();}
function download(name,content,type='application/json'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},1000);}
async function exportProject(pack=false,selection=false){try{const p=selection?P.subset(App.project,App.currentId):App.project;if(pack)download(slug(p.title)+'.chronea',await S.pack(p,App.assets));else download(slug(p.title)+(selection?'-chronologie':'')+'.chronea.json',JSON.stringify(await S.portable(p,App.assets),null,2));App.lastFileSave=new Date().toLocaleTimeString('fr-FR');status('Fichier projet exporté — conserve cette copie');}catch(error){toast(error.message);}}
async function saveFile(){if(typeof showSaveFilePicker!=='function'){await exportProject();return;}try{if(!App.fileHandle)App.fileHandle=await showSaveFilePicker({suggestedName:slug(App.project.title)+'.chronea',types:[{description:'Projet Chronéa',accept:{'application/zip':['.chronea']}}]});const writable=await App.fileHandle.createWritable();await writable.write(await S.pack(App.project,App.assets));await writable.close();App.lastFileSave=new Date().toLocaleTimeString('fr-FR');status('Projet enregistré dans le fichier');}catch(error){if(error.name!=='AbortError'){toast('Enregistrement direct indisponible — téléchargement JSON de secours.');await exportProject();}}}
function legacyTimeline(t=currentTimeline()){
 const s=system(t);if(s.type==='customCalendar')throw new Error('Ce format ne porte pas un calendrier personnalisé.');
 const q=value=>value==='approximate'?'about':value||'exact';
 const result={id:t.id,name:t.title,timeMode:s.type==='numeric'?'universal':'calendar',unit:s.definition.unit||'cycle',events:t.events.filter(e=>{const ep=[e.temporal.start,e.temporal.end].filter(Boolean);return !ep.some(a=>a.notBefore!==undefined||a.notAfter!==undefined)&&!(ep.length===2&&ep[0].qualifier!==ep[1].qualifier);}).map(e=>{
  const a=e.temporal.start||e.temporal.end,b=e.temporal.kind==='interval'?e.temporal.end:null;let time={};const qualifier=e.temporal.kind==='openInterval'?(e.temporal.start?'after':'before'):q(a?.qualifier);
  if(s.type==='numeric')time={start:a?.value??'',end:b?.value??'',unit:a?.unit||s.definition.unit,qualifier};else{time={kind:b?'range':'point',certainty:qualifier};for(const [prefix,ep]of [['start',a],['end',b]])for(const key of ['year','month','day'])time[prefix+key[0].toUpperCase()+key.slice(1)]=ep?.value[key]??'';if(a?.value.hour!==undefined)time.ical={start:T.icsEndpoint(a.value),...(b?.value.hour!==undefined?{end:T.icsEndpoint(b.value)}:{})};}
  return {id:e.id,title:e.title,kind:e.type,color:e.color,dateLabel:e.displayDate,summary:e.summary,markdown:e.markdown,group:eventLane(e,t),tags:e.tags,location:e.place,sources:sourceText(e),links:e.links,time,attachments:[],relations:t.relations.filter(r=>r.type==='related'&&r.direction==='undirected'&&(r.sourceId===e.id||r.targetId===e.id)).map(r=>r.sourceId===e.id?r.targetId:r.sourceId),externalIds:e.externalIds,icalRelations:e.metadata?.icalRelations||[]};})};const included=new Set(result.events.map(e=>e.id));for(const e of result.events)e.relations=e.relations.filter(id=>included.has(id));return result;
}
function exportCSV(){const result=D.csv(App.project,App.currentId);download(slug(currentTimeline().title)+'.csv',result.text,'text/csv;charset=utf-8');toast(result.omitted+' média(s) local(aux) omis ; temporalité et relations conservées dans les colonnes JSON.');}
function exportJSCalendar(){const result=D.jscalendar(App.project,App.currentId);download(slug(currentTimeline().title)+'-jscalendar.json',JSON.stringify(result.data,null,2));toast(result.skipped.length+' repère(s) non représentable(s) omis.');}
function exportICS(){const t=legacyTimeline(),result=C.toICS(t);download(slug(t.name)+'.ics',result.text,'text/calendar');toast((result.skipped+currentTimeline().events.length-t.events.length)+' dates non représentables omises. Médias et relations riches nécessitent le JSON natif.');}
function exportPreceden(){const t=legacyTimeline(),rows=[['layer_name','event_id','event_name','notes','start_date','end_date','icon','color']];for(const e of t.events){if(t.timeMode!=='calendar'||e.time.startYear===''||['before','after','uncertain'].includes(e.time.certainty))continue;const parts=prefix=>T.valueText(Object.fromEntries(['year','month','day'].filter(k=>e.time[prefix+k[0].toUpperCase()+k.slice(1)]!=='').map(k=>[k,e.time[prefix+k[0].toUpperCase()+k.slice(1)]])),system());rows.push([e.group,e.id,e.title,[e.summary,e.markdown,e.sources].filter(Boolean).join('\n\n'),(e.time.certainty==='about'?'~':'')+parts('start'),e.time.kind==='range'?parts('end'):'','',e.color.slice(1)]);}download(slug(t.name)+'-preceden.csv',C.csvRows(rows),'text/csv');toast('Preceden : médias, relations et nuances avancées non conservés.');}
async function exportTimelineJS(){const t=currentTimeline(),s=system();if(s.type!=='gregorian')throw new Error('TimelineJS nécessite des dates grégoriennes.');const events=[];for(const e of t.events){const a=e.temporal.start||e.temporal.end,b=e.temporal.kind==='interval'?e.temporal.end:null;if(!a?.value.year&&a?.value.year!==0)continue;const item={start_date:{...a.value},text:{headline:esc(e.title),text:markdown([e.summary,e.markdown].filter(Boolean).join('\n\n'))},display_date:eventLabel(e),group:eventLane(e)};if(b)item.end_date={...b.value};const media=eventMedia(e)[0];if(media)item.media={url:media.remoteUrl||await S.dataURL(App.assets.get(media.storageRef)),caption:media.caption||'',alt:media.alt||''};events.push(item);}download(slug(t.title)+'-timelinejs.json',JSON.stringify({title:{text:{headline:esc(t.title),text:''}},events},null,2));toast('TimelineJS : temporalité complexe affichée par libellé ; relations et sources omises.');}
function exportJSONLD(){download(slug(currentTimeline().title)+'.jsonld',JSON.stringify(D.jsonld(App.project,App.currentId),null,2),'application/ld+json');}
function reportMarkdown(events=null,title=null){const options=publicationOptions();events=events||publicationEvents(options);title=title||options.title;const has=key=>options.fields.split(',').includes(key);return '# '+title+'\n\n'+(options.subtitle?options.subtitle+'\n\n':'')+events.map(e=>'## '+e.title+'\n\n'+[has('date')?'**'+eventLabel(e)+'**':'',has('summary')?e.summary:'',has('markdown')?e.markdown:'',has('place')&&e.place?'Lieu : '+e.place:'',has('lane')&&options.lanes&&eventLane(e)?'Fil : '+eventLane(e):'',has('tags')&&e.tags.length?'Tags : '+e.tags.join(', '):'',options.sources&&sourceText(e)?'Sources :\n'+sourceText(e):'',has('links')?parsedLinks(e.links).map(l=>'- ['+l.label+']('+l.url+')').join('\n'):'',has('relations')?relationText(e):'',has('media')?eventMedia(e).map(m=>'- Fichier : '+m.name+(m.caption?' — '+m.caption:'')).join('\n'):''].filter(Boolean).join('\n\n')).join('\n\n');}
async function reportHTML(){return publicationHTML();}
function relationText(e,t=currentTimeline()){return t.relations.filter(r=>r.sourceId===e.id||r.targetId===e.id).map(r=>{const other=t.events.find(x=>x.id===(r.sourceId===e.id?r.targetId:r.sourceId));return (r.direction==='directed'?(r.sourceId===e.id?'→ ':'← '):'↔ ')+(ChroneaRelationLabels[r.type]||r.type)+' : '+(other?.title||'')+(r.note?' — '+r.note:'');}).join('\n');}
function reportTeX(){const fields=publicationOptions().fields.split(','),has=key=>fields.includes(key);return '\\documentclass{article}\n\\usepackage[T1]{fontenc}\n\\usepackage[utf8]{inputenc}\n\\usepackage[french]{babel}\n\\usepackage{hyperref}\n\\begin{document}\n\\section*{'+U.texEscape(publicationOptions().title)+'}\n'+publicationEvents(publicationOptions()).map(e=>'\\subsection*{'+U.texEscape(e.title)+'}\n'+(has('date')?U.texEscape(eventLabel(e))+'\\par\n':'')+(has('summary')?U.texEscape(e.summary)+'\\par\n':'')+(has('markdown')?U.markdownTeX(e.markdown):'')+U.texEscape([has('place')?e.place:'',has('lane')?eventLane(e):'',has('tags')?e.tags.join(', '):'',publicationOptions().sources?sourceText(e):'',has('links')?e.links:'',has('relations')?relationText(e):'',has('media')?eventMedia(e).map(m=>'Fichier : '+m.name).join('\n'):''].filter(Boolean).join('\n'))+'\\par\n').join('\n')+'\\end{document}\n';}
function publicationOptions(){const margin=Number($('#pubMargin').value);if(!Number.isFinite(margin)||margin<0||margin>40)throw Error('Choisis des marges entre 0 et 40 mm.');const density=$('#pubDensity').value,fields=density==='compact'?'date':density==='summary'?$('#pubFields').value.split(',').filter(key=>key!=='markdown').join(','):$('#pubFields').value;return {title:$('#pubTitle').value||currentTimeline().title,subtitle:$('#pubSubtitle').value,format:$('#pubFormat').value,orientation:$('#pubOrientation').value,margin,fields,media:$('#pubMedia').checked,sources:$('#pubSources').checked,lanes:$('#pubLanes').checked,spans:$('#pubSpans').checked,legend:$('#pubLegend').checked,range:$('#pubRange').checked};}
function publicationEvents(options,t=currentTimeline()){return options.range?filteredEvents(t):t.events.slice().sort((a,b)=>(eventRange(a,t).anchor??Infinity)-(eventRange(b,t).anchor??Infinity));}
async function publicationSVG(){const options=publicationOptions(),t=currentTimeline(),events=publicationEvents(options);return U.svg(App.project,t,events,options.range&&App.prefs.rangeFilter?App.prefs.rangeFilter:bounds(t),options,{lane:eventLane,source:sourceText,relations:relationText,assets:App.assets});}
async function publicationReport(events,t,options){const fields=new Set(options.fields.split(',')),parts=[];for(const e of events){const media=eventMedia(e);parts.push(`<article><h2>${esc(e.title)}</h2>${fields.has('date')?`<p>${esc(eventLabel(e,t))}</p>`:''}${fields.has('summary')?`<p>${esc(e.summary)}</p>`:''}${fields.has('markdown')?markdown(e.markdown):''}${fields.has('place')?`<p>${esc(e.place)}</p>`:''}${fields.has('lane')&&options.lanes?`<p>Fil : ${esc(eventLane(e,t))}</p>`:''}${fields.has('tags')?`<p>${esc(e.tags.join(', '))}</p>`:''}${options.sources?`<pre>${esc(sourceText(e))}</pre>`:''}${fields.has('links')?parsedLinks(e.links).map(l=>`<p><a href="${esc(l.url)}">${esc(l.label)}</a></p>`).join(''):''}${fields.has('relations')?`<pre>${esc(relationText(e,t))}</pre>`:''}${fields.has('media')?media.map(m=>`<p>Fichier : ${esc(m.name)} ${esc(m.caption||'')}</p>`).join(''):''}${options.media?(await Promise.all(media.filter(m=>!m.remoteUrl&&m.mimeType.startsWith('image/')).map(async m=>`<img src="${esc(await S.dataURL(App.assets.get(m.storageRef)))}" alt="${esc(m.alt||e.title)}">`))).join(''):''}</article>`);}return '<section><h1>'+esc(options.title||t.title)+'</h1><p>'+esc(options.subtitle)+'</p>'+parts.join('')+'</section>';}
async function publicationHTML(){const options=publicationOptions(),content=await publicationReport(publicationEvents(options),currentTimeline(),options);return '<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+esc(options.title)+'</title><style>body{font:17px/1.6 Georgia,serif;max-width:950px;margin:30px auto;padding:20px;color:#222;background:#fff}article{break-inside:avoid;border-bottom:1px solid #aaa;padding:20px 0}pre{white-space:pre-wrap}img{max-width:100%;max-height:350px}@media print{@page{size:'+options.format+' '+options.orientation+';margin:'+options.margin+'mm}body{margin:0;padding:0;max-width:none}}</style><body>'+content+'</body></html>';}
async function printPublication(all=false){try{const options=publicationOptions(),parts=[];for(const t of all?App.project.timelines:[currentTimeline()]){const events=all?t.events:publicationEvents(options,t),title=all?t.title:options.title,graph=await U.svg(App.project,t,events,!all&&options.range&&App.prefs.rangeFilter?App.prefs.rangeFilter:bounds(t),{...options,title,fields:'',sources:false,media:false},{lane:eventLane,source:sourceText,relations:relationText,assets:App.assets});parts.push('<section class="print-scale">'+graph+'</section>');parts.push(await publicationReport(events,t,{...options,title}));}$('#publicationPrint').innerHTML='<div class="publication-report">'+parts.join('')+'</div>';$('#publicationPageStyle').textContent='@media print{@page{size:'+options.format+' '+options.orientation+';margin:'+options.margin+'mm}}';if($('#publicationDialog').open)$('#publicationDialog').close();if($('#exportDialog').open)$('#exportDialog').close();document.body.classList.add('publication-print');window.print();}catch(error){toast(error.message);}}
async function openPublication(){$('#pubTitle').value=currentTimeline().title;$('#publicationDialog').showModal();await previewPublication();}
async function previewPublication(){try{$('#publicationPreview').innerHTML=await publicationSVG();}catch(error){toast(error.message);}}
function plainHTML(value){const text=String(value||'').replace(/<(script|style|iframe|object|embed)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'').replace(/<br\b[^>]*>|<\/(?:p|div|li|h[1-6]|blockquote)\s*>/gi,'\n').replace(/<[^>]*>/g,'').replace(/</g,'&lt;').replace(/>/g,'&gt;');return new DOMParser().parseFromString('<body>'+text+'</body>','text/html').body.textContent.trim();}
async function timelineJSImport(data){const legacy={version:2,currentId:'import-timeline',timelines:[{id:'import-timeline',name:plainHTML(data.title?.text?.headline)||'TimelineJS',timeMode:'calendar',events:[]}]};for(const item of data.events){const a=item.start_date,b=item.end_date;if(!a)throw new Error('Date TimelineJS absente.');const attachments=[];if(item.media?.url){const url=item.media.url;if(url.startsWith('data:')){const type=url.slice(5,url.indexOf(';')),payload=url.split(',')[1];attachments.push({id:P.id(),name:'Média',type,size:atob(payload).length,dataUrl:url});}else attachments.push({id:P.id(),name:'Média distant',type:'text/uri-list',size:0,remoteUrl:url});}legacy.timelines[0].events.push({id:P.id(),title:plainHTML(item.text?.headline)||'Sans titre',summary:'',markdown:plainHTML(item.text?.text),group:item.group||'',dateLabel:item.display_date||'',tags:[],relations:[],attachments,time:{kind:b?'range':'point',certainty:'exact',startYear:a.year??'',startMonth:a.month??'',startDay:a.day??'',endYear:b?.year??'',endMonth:b?.month??'',endDay:b?.day??''}});}const result=P.fromLegacy(legacy);for(const [i,e]of result.project.timelines[0].events.entries()){const item=data.events[i];for(const [key,field]of [['start','start_date'],['end','end_date']])if(e.temporal[key]&&item[field]?.hour!==undefined){for(const component of ['hour','minute','second'])if(item[field][component]!==undefined)e.temporal[key].value[component]=Number(item[field][component]);e.temporal[key].precision=T.precision(e.temporal[key].value,result.project.timeSystems[0]);}}P.validate(result.project);for(const [ref,url]of result.assets){const m=result.project.media.find(m=>m.storageRef===ref);result.assets.set(ref,S.fromDataURL(url,m.mimeType,m.size));}await S.validateAssets(result.project,result.assets);return result;}
async function previewImport(result){$('#importDetails').innerHTML='<h3>Aperçu avant application</h3>'+result.project.timelines.map(t=>'<h4>'+esc(t.title)+'</h4><ul>'+t.events.slice(0,6).map(e=>'<li>'+esc(e.title)+' — '+esc(T.label(e.temporal,result.project.timeSystems.find(s=>s.id===t.timeSystemId)))+'</li>').join('')+'</ul>').join('');$('#importPreviewText').textContent=result.project.timelines.length+' chronologie(s), '+result.project.timelines.reduce((n,t)=>n+t.events.length,0)+' repère(s). '+(result.warnings||[]).join(' ; ');const dialog=$('#importPreviewDialog');dialog.returnValue='';dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='apply'),{once:true}));}
function confirmFidelity(format){const capabilities=D.CAPABILITIES[format];if(!capabilities)return Promise.resolve(true);$('#fidelityContent').innerHTML='<table class="table-view"><thead><tr><th>Élément</th><th>Traitement</th></tr></thead><tbody>'+Object.entries(capabilities).map(([key,value])=>`<tr><th>${esc(({temporal:'Temporalité',systems:'Systèmes temporels',media:'Médias',relations:'Relations',sources:'Sources'})[key])}</th><td>${esc(value)}</td></tr>`).join('')+'</tbody></table>';const dialog=$('#fidelityDialog');dialog.returnValue='';dialog.showModal();return new Promise(resolve=>{const button=$('#fidelityApply'),apply=()=>dialog.close('apply');button.addEventListener('click',apply);dialog.addEventListener('close',()=>{button.removeEventListener('click',apply);resolve(dialog.returnValue==='apply');},{once:true});});}
async function mapCSV(text,name){const rows=C.parseCSV(text),headers=rows[0];if(headers.includes('project_json')||headers.includes('time_mode'))return D.readCSV(text,name);const fields=[['title','Titre',['title','titre','event_name','headline','name','nom']],['start','Début / EDTF',['start_date','start','date','debut','début','edtf']],['end','Fin',['end_date','end','fin']],['summary','Résumé',['summary','description','notes','résumé']],['markdown','Texte complet',['markdown','text','texte']],['lane','Fil',['group','lane','layer_name','fil']],['tags','Tags',['tags']],['place','Lieu',['location','place','lieu']],['source','Source',['sources','source']],['id','Identifiant externe',['id','uid','event_id']]];$('#csvMappingFields').innerHTML=fields.map(([key,label,aliases])=>{const guess=headers.findIndex(h=>aliases.includes(h.trim().toLowerCase()));return `<label class="field">${esc(label)}<select data-map="${key}"><option value="">Ignorer</option>${headers.map((h,i)=>`<option value="${i}" ${i===guess?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`;}).join('');$('#csvDetected').textContent='Séparateur : '+(C.detectDelimiter(text)==='\t'?'tabulation':C.detectDelimiter(text))+' · texte décodé UTF-8 · '+(rows.length-1)+' ligne(s). Les valeurs source restent intactes avant confirmation.';let result;
 const convert=()=>{try{const mapping=Object.fromEntries($$('[data-map]').map(el=>[el.dataset.map,el.value]));mapping.mode=$('#csvMode').value;mapping.unit=$('#csvUnit').value;mapping.direction=$('#csvDirection').value;result=D.readCSV(text,name,mapping);$('#csvErrors').textContent=result.errors.slice(0,100).map(e=>'Ligne '+e.line+' : '+e.message).join('\n');$('#csvConversions').innerHTML='<table class="table-view"><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'<th>Conversion temporelle</th></tr></thead><tbody>'+rows.slice(1,7).map((row,i)=>'<tr>'+row.map(value=>'<td>'+esc(value.slice(0,160))+'</td>').join('')+'<td>'+esc(result.project.timelines[0].events[i]?T.label(result.project.timelines[0].events[i].temporal,result.project.timeSystems[0]):'voir erreurs')+'</td></tr>').join('')+'</tbody></table>';$('#csvApply').disabled=!!result.errors.length;}catch(error){result=null;$('#csvErrors').textContent=error.message;$('#csvApply').disabled=true;}};
 const dialog=$('#csvMappingDialog'),button=$('#csvApply'),apply=()=>dialog.close('apply');dialog.returnValue='';dialog.addEventListener('change',convert);button.addEventListener('click',apply);convert();dialog.showModal();return new Promise(resolve=>dialog.addEventListener('close',()=>{dialog.removeEventListener('change',convert);button.removeEventListener('click',apply);resolve(dialog.returnValue==='apply'?result:null);},{once:true}));}
function canCombineImport(p){const active=projectSystem();return !isMixedProject()&&p.timelines.every(t=>{const sys=p.timeSystems.find(s=>s.id===t.timeSystemId);return sys.type===active.type&&JSON.stringify(sys.definition)===JSON.stringify(active.definition);});}
function applyImport(result,destination){P.validate(result.project);if(result.errors?.length)throw Error('Corrige les erreurs avant l’import.');if(destination==='replace'){return commit((draft,assets)=>{Object.assign(draft,result.project);assets.clear();for(const [ref,blob]of result.assets)assets.set(ref,blob);},'Projet restauré.');}if(!canCombineImport(result.project))throw Error('Ce fichier utilise un autre système temporel. Crée un nouveau projet pour l’ouvrir.');if(['merge','update'].includes(destination)){const merged=D.merge(App.project,App.assets,result.project,result.assets,App.currentId,destination==='update');return commit((draft,assets)=>{Object.assign(draft,merged.project);for(const [ref,blob]of merged.assets)assets.set(ref,blob);},'Fusion appliquée.');}const incoming=D.rebase(result.project,result.assets);return commit((draft,assets)=>{incoming.project.timelines.forEach(t=>t.timeSystemId=projectSystem().id);draft.timelines.push(...incoming.project.timelines);draft.media.push(...incoming.project.media);draft.sources.push(...incoming.project.sources);for(const [ref,blob]of incoming.assets)assets.set(ref,blob);},'Chronologies ajoutées.');}
async function importInterchange(file){try{if(file.size>S.MAX_BYTES)throw Error('256 Mo maximum par fichier.');const name=file.name.toLowerCase();let result;if(name.endsWith('.chronea'))result=await S.unpack(file);else{const text=await file.text();if(/\.(csv|tsv)$/.test(name)){result=await mapCSV(text,file.name);if(!result)return;}else if(/^\s*BEGIN:VCALENDAR/.test(text)){const parsed=C.fromICS(text,P.id,file.name);result={...P.fromLegacy({version:2,currentId:parsed.timeline.id,timelines:[parsed.timeline]}),warnings:parsed.warnings,assets:new Map()};}else{const data=JSON.parse(text);result=['Event','Group'].includes(data['@type'])?D.readJSCalendar(data):Array.isArray(data.events)?await timelineJSImport(data):await S.readJSON(data);}}P.validate(result.project);if(!await previewImport(result))return;let destination=$('#importDestination').value;if(destination!=='replace'&&!canCombineImport(result.project)){const dialog=$('#incompatibleImportDialog');dialog.returnValue='';dialog.showModal();const decision=await new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue),{once:true}));if(decision!=='new')return;if(!await flushSave())throw Error('Enregistre le projet courant dans un fichier avant d’ouvrir l’import.');const rebased=D.rebase(result.project,result.assets);result={...result,...rebased};destination='replace';}if(destination==='replace'&&!confirm('Remplacer le projet actuel ? Cette action peut être annulée.'))return;if(!applyImport(result,destination))return;App.currentId=destination==='replace'?App.project.timelines[0].id:destination==='add'?App.project.timelines.at(-1).id:App.currentId;App.prefs.scaleCamera=null;App.clusterFilter=null;App.prefs.group='';App.prefs.search='';App.prefs.page=0;App.rangeCache=new WeakMap();render();if($('#exportDialog').open)$('#exportDialog').close();toast('Import validé et appliqué ; annulation disponible.');}catch(error){toast('Import refusé : '+error.message);}}
async function showRecovery(){
 const rows=await App.store.snapshots(App.blocked?(App.store.lastReadId||App.project.id):App.project.id).catch(()=>[]);if(!App.blocked&&!rows.length){toast('Aucun instantané disponible.');return;}
 $('#recoveryText').textContent=App.blocked?'Le contenu original est préservé. Aucune sauvegarde automatique ne le remplacera. Exporte le contenu brut avant de restaurer un instantané.':'Choisis un instantané à restaurer. Tu pourras annuler la restauration.';
 $('#recoverySnapshots').innerHTML=rows.map((row,i)=>`<button class="btn" data-snapshot-index="${i}">Restaurer ${esc(row.at||'la sauvegarde précédente')}</button>`).join('');
 $$('[data-snapshot-index]').forEach(button=>button.addEventListener('click',async()=>{try{const result=await App.store.restoreSnapshot(rows[Number(button.dataset.snapshotIndex)]);if(App.blocked&&!archiveRecovery())return;recordHistory();App.project=result.project;App.assets=result.assets;App.currentId=App.project.timelines[0].id;App.blocked=false;App.revision++;persist();render();$('#recoveryDialog').close();}catch(error){toast(error.message);}}));$('#exportRecovery').classList.toggle('hidden',!App.recoveryRaw);$('#newAfterRecovery').classList.toggle('hidden',!App.blocked);$('#recoveryDialog').showModal();
}
function archiveRecovery(){try{localStorage.setItem('chronea.corrupt-backup.'+Date.now(),App.recoveryRaw||'');return true;}catch{toast('Archivage local impossible. Exporte le contenu original, puis travaille dans cette session.');return false;}}
function changeRange(){try{const s=system(),a=T.parseValue($('#rangeFrom').value,s),b=T.parseValue($('#rangeTo').value,s);if(a===null&&b===null)App.prefs.rangeFilter=null;else{const full=bounds(),min=a===null?full.min:T.valueBounds(a,s).min,max=b===null?full.max:T.valueBounds(b,s).max;if(min===null||max===null||min>=max)throw new Error('La plage doit avoir un début inférieur à la fin.');App.prefs.rangeFilter={min,max};}App.prefs.page=0;savePrefs();render();}catch(error){toast(error.message);}}
function bind(){
 $('#newEventRelation').addEventListener('click',()=>newRelation(App.editingId));$('#relationList').addEventListener('click',event=>{const button=event.target.closest('[data-remove-event-relation]');if(!button)return;if(commit(p=>{const t=p.timelines.find(t=>t.id===App.currentId);t.relations=t.relations.filter(r=>r.id!==button.dataset.removeEventRelation);},'Relation retirée.'))renderRelations(currentTimeline().events.find(e=>e.id===App.editingId));});
 $('#manageLanesBtn').addEventListener('click',openLanes);$('#saveLanesBtn').addEventListener('click',saveLanes);$('#addLaneBtn').addEventListener('click',()=>{captureLaneRows();openNewLane('manager');});$('#eventGroup').addEventListener('change',()=>{if($('#eventGroup').value==='__new'){$('#eventGroup').value='';openNewLane('event');}});$('#saveNewLane').addEventListener('click',saveNewLane);$('#cancelNewLane').addEventListener('click',()=>$('#newLaneDialog').close());$('#laneRows').addEventListener('click',event=>{const button=event.target.closest('[data-lane-move]');if(!button)return;captureLaneRows();const i=Number(button.dataset.laneMove),j=i+Number(button.dataset.laneStep),rows=App.editingLanes;if(j>=0&&j<rows.length)[rows[i],rows[j]]=[rows[j],rows[i]];renderLaneRows();});
 $('#calendarDefinitionFields').addEventListener('click',event=>{const target=event.target.closest('[data-calendar-add],[data-calendar-action]');if(!target)return;captureCalendarRows();if(target.dataset.calendarAdd){const key=target.dataset.calendarAdd;App.calendarRows[key].push(key==='months'?{name:'Nouveau mois',days:30}:{name:'Nouvelle ère',offset:0});}else{const key=target.dataset.calendarKey,i=Number(target.dataset.calendarIndex),action=target.dataset.calendarAction,list=App.calendarRows[key];if(action==='remove')list.splice(i,1);else{const j=i+(action==='up'?-1:1);if(j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];}}renderCalendarRows();});
 $('#addSourceBtn').addEventListener('click',()=>openSource());$('#saveSourceBtn').addEventListener('click',saveSource);$('#sourceList').addEventListener('click',event=>{const target=event.target.closest('[data-edit-source],[data-unlink-source]');if(!target)return;if(target.dataset.editSource)openSource(target.dataset.editSource);else{App.pendingSources=App.pendingSources.filter(s=>s.id!==target.dataset.unlinkSource);renderSources();}});
 $$('[data-pub-field]').forEach(el=>el.addEventListener('change',()=>{$('#pubFields').value=$$('[data-pub-field]').filter(el=>el.checked).map(el=>el.dataset.pubField).join(',');}));

 $('#newSpanBtn').addEventListener('click',()=>openSpan());$('#spanRows').addEventListener('click',event=>{const button=event.target.closest('[data-edit-span]');if(button)openSpan(button.dataset.editSpan);});$('#saveSpanBtn').addEventListener('click',saveSpan);$('#deleteSpanBtn').addEventListener('click',()=>{if(confirm('Supprimer cette ère / phase ?')){commit(p=>{const t=p.timelines.find(x=>x.id===App.currentId);t.spans=t.spans.filter(s=>s.id!==App.editingSpanId);});$('#spanDialog').close();renderSpanRows();}});

 $('#reopenProject').addEventListener('click',reopenProject);
 $('#publicationBtn').addEventListener('click',openPublication);$('#pubPreview').addEventListener('click',previewPublication);for(const [id,handler]of Object.entries({pubSVG:async()=>download(slug(currentTimeline().title)+'.svg',await publicationSVG(),'image/svg+xml'),pubPNG:async()=>download(slug(currentTimeline().title)+'.png',await U.png(await publicationSVG(),Number($('#pubResolution').value)),'image/png'),pubHTML:async()=>download(slug(currentTimeline().title)+'-publication.html',await publicationHTML(),'text/html'),pubPrint:()=>printPublication(),pubPrintAll:()=>printPublication(true)}))$('#'+id).addEventListener('click',async()=>{try{await handler()}catch(error){toast(error.message)}});window.addEventListener('afterprint',()=>{document.body.classList.remove('publication-print');$('#publicationPrint').innerHTML='';});

 $('#canvasInner').addEventListener('click',event=>{const target=event.target.closest('[data-bulk],[data-cluster],[data-clear-cluster],[data-new-relation],[data-remove-relation],[data-reset-filters]');if(!target)return;if(target.hasAttribute('data-reset-filters')){App.prefs.search='';App.prefs.group='';App.prefs.rangeFilter=null;App.clusterFilter=null;App.prefs.page=0;savePrefs();render();return;}if(target.hasAttribute('data-bulk'))bulk(target.dataset.bulk);else if(target.hasAttribute('data-cluster')){App.clusterFilter=new Set(target.dataset.cluster.split(','));App.prefs.view='table';App.prefs.page=0;render();}else if(target.hasAttribute('data-clear-cluster')){App.clusterFilter=null;render();}else if(target.hasAttribute('data-new-relation'))newRelation();else if(target.hasAttribute('data-remove-relation'))commit(p=>{const t=p.timelines.find(x=>x.id===App.currentId);t.relations=t.relations.filter(r=>r.id!==target.dataset.removeRelation);});});
 $('#canvasInner').addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)&&event.target.matches('.scale-node')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
 $('#canvasInner').addEventListener('change',event=>{const el=event.target;if(el.hasAttribute('data-select')){if(el.checked)App.selected.add(el.dataset.select);else App.selected.delete(el.dataset.select);updateSelectionTools();}else if(el.hasAttribute('data-edit')){if(el.dataset.edit==='title'&&!el.value.trim()){toast('Le titre est nécessaire.');return;}const value=el.value;commit(p=>{const e=p.timelines.find(t=>t.id===App.currentId).events.find(e=>e.id===el.dataset.event);e[el.dataset.edit]=el.dataset.edit==='tags'?value.split(',').map(x=>x.trim()).filter(Boolean):value;e.updatedAt=P.stamp();},null,{render:false,clearSelection:false});}else if(el.hasAttribute('data-table-sort')){App.prefs.sort=el.value;savePrefs();render();}else if(el.hasAttribute('data-column')){const columns=new Set(App.prefs.columns.split(',').filter(key=>Object.hasOwn(TABLE_COLUMNS,key)));if(el.checked)columns.add(el.dataset.column);else columns.delete(el.dataset.column);App.prefs.columns=[...columns].join(',');savePrefs();render();}else if(el.hasAttribute('data-relation-filter')){App.prefs.relationType=el.value;App.prefs.page=0;render();}});
 $('#saveRelation').addEventListener('click',()=>{const sourceId=$('#relationSource').value,targetId=$('#relationTarget').value;if(sourceId===targetId){toast('Choisis deux événements distincts.');return;}if(commit(p=>p.timelines.find(t=>t.id===App.currentId).relations.push({id:P.id(),sourceId,targetId,type:$('#relationType').value,direction:relationDirection($('#relationType').value),note:$('#relationNote').value.trim()}),'Relation créée.')){$('#relationDialog').close();if($('#eventDrawer').classList.contains('open'))renderRelations(currentTimeline().events.find(e=>e.id===App.editingId));}});

 $('#canvasInner').addEventListener('click',event=>{const target=event.target.closest('[data-open-event],[data-empty-add],[data-empty-demo],[data-page]');if(!target)return;if(target.hasAttribute('data-open-event'))openEditor(target.dataset.openEvent);else if(target.hasAttribute('data-empty-add'))openEditor();else if(target.hasAttribute('data-empty-demo'))loadDemo();else{App.prefs.page=Number(target.dataset.page);render();$('#canvas').scrollTop=0;}});
 $('#timelineSelect').addEventListener('change',event=>{App.currentId=event.target.value;App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.group='';App.selected.clear();App.prefs.page=0;savePrefs();render();});
 $('#viewSeg').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button){App.prefs.view=button.dataset.view;App.prefs.page=0;savePrefs();render();}});
 for(const [selector,key]of [['#densitySelect','density'],['#groupFilter','group'],['#themeSelect','theme'],['#styleSelect','style']])$(selector).addEventListener('change',event=>{App.prefs[key]=event.target.value;App.prefs.page=0;savePrefs();render();});
 $('#searchInput').addEventListener('input',event=>{App.prefs.search=event.target.value;App.prefs.page=0;clearTimeout(App.searchTimer);App.searchTimer=setTimeout(()=>{savePrefs();render();},100);});
 $('#addEventBtn').addEventListener('click',()=>openEditor());for(const selector of ['#closeDrawer','#cancelEventBtn','#drawerBackdrop'])$(selector).addEventListener('click',closeEditor);
 $('#saveEventBtn').addEventListener('click',saveEvent);$('#eventForm').addEventListener('submit',event=>{event.preventDefault();saveEvent();});$('#deleteEventBtn').addEventListener('click',deleteEvent);$$('[name=elementShape]').forEach(el=>el.addEventListener('change',()=>setFormShape(formShape())));
 $('#eventFiles').addEventListener('change',event=>{handleFiles(event.target.files);event.target.value='';});$('#attachmentList').addEventListener('click',event=>{const button=event.target.closest('[data-remove-media]');if(button){captureAttachments();App.pendingMedia.splice(Number(button.dataset.removeMedia),1);renderAttachments(false);}});
 $('#eventDrawer').addEventListener('keydown',event=>{if(event.key!=='Tab')return;const items=$$('#eventDrawer button:not(:disabled),#eventDrawer input:not(:disabled),#eventDrawer select,#eventDrawer textarea').filter(el=>el.getClientRects().length),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
 for(const [selector,handler]of Object.entries({'#timelineManageBtn':openTimelineDialog,'#saveTimelineBtn':saveTimelineSettings,'#newTimelineBtn':newTimeline,'#duplicateTimelineBtn':duplicateTimeline,'#deleteTimelineBtn':deleteTimeline,'#loadDemoBtn':loadDemo,'#undoBtn':()=>undo(),'#redoBtn':()=>undo(true),'#saveProjectBtn':saveFile,'#exportRecovery':()=>download('chronea-original-brut.txt',App.recoveryRaw||'','text/plain'),'#recoveryBtn':showRecovery,'#projectBtn':openProjectDialog}))$(selector).addEventListener('click',handler);
 $('#projectTimeMode').addEventListener('change',()=>{const mode=$('#projectTimeMode').value,type=mode==='custom'?'customCalendar':mode==='universal'?'numeric':'gregorian',definition=type==='customCalendar'?{months:[{name:'Aube',days:30},{name:'Clair',days:30}],intercalaryDays:1,eras:[{name:'Fondation',offset:0}],higherUnits:[],displayFormat:'jour mois année ère'}:type==='numeric'?{unit:'cycle',direction:1}:{};fillSystemDefinition({type,definition});projectTimePreview();});
 $$('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>$('#'+button.dataset.closeDialog).close()));
 $('#newAfterRecovery').addEventListener('click',()=>{if(confirm('Archiver l’original et reprendre la sauvegarde locale ?')&&archiveRecovery()){App.blocked=false;persist();$('#recoveryDialog').close();}});
 $('#projectRename').addEventListener('click',()=>{const title=prompt('Nom du projet :',App.project.title);if(title)commit(p=>p.title=title,'Projet renommé.');});
 $('#projectNew').addEventListener('click',()=>openProjectTime());$('#projectTimeBtn').addEventListener('click',openProjectTime);$('#projectTimeApply').addEventListener('click',saveProjectTime);$('#projectTimeNew').addEventListener('click',async()=>{try{const next=selectedProjectSystem();if(await createNewProject(next)){$('#projectTimeDialog').close();$('#projectDialog').close();}}catch(error){toast(error.message);}});$('#splitMixedProject').addEventListener('click',splitMixedProject);$('#keepMixedProject').addEventListener('click',()=>$('#projectDialog').close());
 $('#projectSnapshots').addEventListener('click',()=>{$('#projectDialog').close();showRecovery();});
 $('#rangeFrom').addEventListener('change',changeRange);$('#rangeTo').addEventListener('change',changeRange);$('#rangeReset').addEventListener('click',()=>{App.prefs.rangeFilter=null;App.clusterFilter=null;App.prefs.page=0;savePrefs();render();});$('#zoomInput').addEventListener('input',event=>zoomScaleAt(2**Number(event.target.value)/getScaleZoomRatio()));$('#panPrev').addEventListener('click',()=>panScale(-1));$('#panNext').addEventListener('click',()=>panScale(1));$('#zoomMinus').addEventListener('click',()=>zoomScaleAt(.5));$('#zoomPlus').addEventListener('click',()=>zoomScaleAt(2));$('#scaleReset').addEventListener('click',resetScaleCamera);
 $('#exportBtn').addEventListener('click',()=>$('#exportDialog').showModal());
 $$('[data-export]').forEach(button=>button.addEventListener('click',async()=>{try{if(!await confirmFidelity(({json:'native',project:'native',package:'native'})[button.dataset.export]||button.dataset.export))return;await ({json:()=>exportProject(false,true),project:()=>exportProject(),package:()=>exportProject(true),csv:exportCSV,ics:exportICS,preceden:exportPreceden,timelinejs:exportTimelineJS,jsonld:exportJSONLD,jscalendar:exportJSCalendar,md:()=>download(slug(currentTimeline().title)+'.md',reportMarkdown(),'text/markdown'),html:async()=>download(slug(currentTimeline().title)+'.html',await reportHTML(),'text/html'),tex:()=>download(slug(currentTimeline().title)+'.tex',reportTeX(),'application/x-tex')}[button.dataset.export]());}catch(error){toast(error.message);}}));
 $('#importInput').addEventListener('change',event=>{const file=event.target.files[0];if(file)importInterchange(file);event.target.value='';});
 document.addEventListener('keydown',event=>{const editing=$('#eventDrawer').classList.contains('open'),modal=document.querySelector('dialog[open]'),field=event.target.matches?.('input,textarea,select');if(event.key==='Escape'&&editing&&!modal)closeEditor();if((event.ctrlKey||event.metaKey)&&!editing&&!modal){if(event.key.toLowerCase()==='k'){event.preventDefault();$('#searchInput').focus();}else if(event.key.toLowerCase()==='n'){event.preventDefault();openEditor();}else if(event.key.toLowerCase()==='z'&&!field){event.preventDefault();undo(event.shiftKey);}else if(event.key.toLowerCase()==='s'){event.preventDefault();saveFile();}}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&App.saveTimer)flushSave();});window.addEventListener('pagehide',()=>{savePrefs();if(App.saveTimer)flushSave();});
}
async function openProjectDialog(){try{const rows=await App.store.projects();$('#cachedProjects').innerHTML='<option value="">Choisir un projet local…</option>'+rows.map(row=>`<option value="${esc(row.id)}">${esc(row.title)} · ${esc(row.updatedAt.slice(0,10))}</option>`).join('');}catch(error){toast(error.message);}$('#projectSystemSummary').textContent=isMixedProject()?'Plusieurs temporalités — compatibilité':projectSystem().name;$('#mixedProjectNotice').hidden=!isMixedProject();$('#projectDialog').showModal();}
async function reopenProject(){const id=$('#cachedProjects').value;if(!id)return;if(!await flushSave()&&!confirm('La sauvegarde locale a échoué. Ouvrir l’autre projet ?'))return;try{const loaded=await App.store.load(id);if(!loaded)throw Error('Projet absent du cache.');recordHistory();revokeURLs();App.project=loaded.project;App.assets=loaded.assets;App.currentId=App.project.timelines[0].id;App.rangeCache=new WeakMap();App.prefs.scaleCamera=null;App.prefs.rangeFilter=null;App.prefs.search='';App.prefs.group='';App.clusterFilter=null;App.fileHandle=null;App.lastFileSave=null;savePrefs();$('#projectDialog').close();render();status(I18N.fr.loaded);}catch(error){toast(error.message);}}
async function init(){
 $('#addEventBtn').disabled=true;$('#canvasInner').textContent='Ouverture du projet local…';let raw=null;
 try{let prefs={};try{prefs=JSON.parse(localStorage.getItem('chronea.preferences.v3')||'{}');}catch{/* Préférences non critiques. */}for(const key of Object.keys(DEFAULT_PREFS))if(prefs[key]!==undefined)App.prefs[key]=prefs[key];if(!['vertical','horizontal','list','gallery','table','relations'].includes(App.prefs.view))App.prefs.view='vertical';for(const key of ['search','group','columns','relationType','sort'])if(typeof App.prefs[key]!=='string')App.prefs[key]=DEFAULT_PREFS[key];if(!['parchment','ink','forest','ocean','night'].includes(App.prefs.theme))App.prefs.theme='parchment';if(!['editorial','minimal','celestial'].includes(App.prefs.style))App.prefs.style='editorial';// L'ancienne caméra devient uniquement une fenêtre graphique.
if(prefs.camera&&!prefs.scaleCamera)App.prefs.scaleCamera=prefs.camera;if(!Number.isInteger(App.prefs.page)||App.prefs.page<0)App.prefs.page=0;for(const key of ['scaleCamera','rangeFilter'])if(App.prefs[key]&&(!Number.isFinite(App.prefs[key].min)||!Number.isFinite(App.prefs[key].max)||App.prefs[key].min>=App.prefs[key].max))App.prefs[key]=null;
 await App.store.open();let loaded=await App.store.load(prefs.projectId);
 if(!loaded){raw=localStorage.getItem('chronea.project.v3');if(raw)loaded=await S.readJSON(JSON.parse(raw));else{raw=localStorage.getItem('chronea.state.v2')||localStorage.getItem('chronea.state.v1');if(raw){loaded=await S.readJSON({app:'Chronéa',schemaVersion:JSON.parse(raw).version||2,kind:'project',state:JSON.parse(raw)});const legacyPrefs=loaded.prefs||{};App.prefs={...App.prefs,...Object.fromEntries(Object.keys(DEFAULT_PREFS).filter(k=>legacyPrefs[k]!==undefined).map(k=>[k,legacyPrefs[k]]))};}}}
 if(loaded){App.project=loaded.project;App.assets=loaded.assets;App.currentId=loaded.currentId||prefs.currentId||App.project.timelines[0].id;}else App.currentId=App.project.timelines[0].id;
 }catch(error){App.blocked=true;App.recoveryRaw=raw||App.store.lastReadRaw||String(error);App.currentId=App.project.timelines[0].id;}
 bind();render();$('#addEventBtn').disabled=isMixedProject();status(App.blocked?I18N.fr.recovery:I18N.fr.loaded);if(App.blocked)showRecovery();else if(!App.store.lastProject)persist();
}
Object.assign(App,{relationDirection,renderRelations,openLanes,saveLanes,openNewLane,saveNewLane,openSource,saveSource,sourceText,isMixedProject,projectSystem,splitProjectBySystem,splitMixedProject,newTimeline,openProjectTime,saveProjectTime,createNewProject,formShape,setFormShape,getFullDomain,getScaleCamera,setScaleCamera,resetScaleCamera,getScaleZoomRatio,zoomScaleAt,panScale,changeRange,filteredEvents,init,commit,render,currentTimeline,system,eventRange,eventLabel,openEditor,closeEditor,saveEvent,deleteEvent,loadDemo,flushSave,undo,importInterchange,exportProject,handleFiles,showRecovery,legacyTimeline,reportHTML,reportMarkdown,saveFile,formTemporal,openTimelineDialog,saveTimelineSettings,bulk,zoomAt,renderScale,newRelation,applyImport,mapCSV,confirmFidelity,publicationOptions,publicationSVG,publicationHTML,publicationReport,printPublication,reportTeX,openPublication,openSpan,saveSpan});
App.init();
})();
