/* Publication vectorielle autonome et conversion Markdown vers TeX. */
const ChroneaPublication=(()=>{
'use strict';const T=ChroneaTime,S=ChroneaStorage,Scale=ChroneaScale,C=ChroneaCore;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const texEscape=v=>String(v??'').replace(/[\\#$%&_{}^~]/g,c=>({'\\':'\\textbackslash{}','^':'\\textasciicircum{}','~':'\\textasciitilde{}'}[c]||'\\'+c));
function texInline(text){let out='',index=0;const expression=/\*\*(.+?)\*\*|\*([^*]+)\*|`([^`]+)`|\[([^\]]+)\]\(([^)]+)\)/g;for(const match of text.matchAll(expression)){out+=texEscape(text.slice(index,match.index));out+=match[1]?'\\textbf{'+texEscape(match[1])+'}':match[2]?'\\emph{'+texEscape(match[2])+'}':match[3]?'\\texttt{'+texEscape(match[3])+'}':C.safeUrl(match[5])?'\\href{'+texEscape(match[5])+'}{'+texEscape(match[4])+'}':texEscape(match[4]);index=match.index+match[0].length;}return out+texEscape(text.slice(index));}
function markdownTeX(text=''){let out='',list=false;for(const line of text.split('\n')){const heading=line.match(/^(#{1,3}) (.+)$/),item=line.match(/^[-*] (.+)$/);if(list&&!item){out+='\\end{itemize}\n';list=false;}if(heading)out+='\\'+(['section','subsection','subsubsection'][heading[1].length-1])+'*{'+texInline(heading[2])+'}\n';else if(item){if(!list){out+='\\begin{itemize}\n';list=true;}out+='\\item '+texInline(item[1])+'\n';}else if(line.startsWith('> '))out+='\\begin{quote}'+texInline(line.slice(2))+'\\end{quote}\n';else out+=texInline(line)+(line?'\n':'\n\\par\n');}return out+(list?'\\end{itemize}\n':'');}
function wrap(text,max=110){const lines=[];for(const paragraph of String(text||'').split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(line.length+word.length>max&&line){lines.push(line);line='';}if(word.length>max){if(line)lines.push(line);for(let i=0;i<word.length;i+=max)lines.push(word.slice(i,i+max));line='';}else line+=(line?' ':'')+word;}lines.push(line);}return lines;}
function textMarkdown(text){return String(text||'').replace(/^#{1,6}\s+/gm,'').replace(/\*\*(.*?)\*\*/g,'$1').replace(/\*(.*?)\*/g,'$1').replace(/`(.*?)`/g,'$1').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1 ($2)');}
async function svg(project,timeline,events,domain,options,context){const system=project.timeSystems.find(s=>s.id===timeline.timeSystemId),width=1100,fields=new Set(options.fields.split(',')),tl={...timeline,lanes:options.lanes?timeline.lanes:[],spans:options.spans?timeline.spans:[]},es=options.lanes?events:events.map(e=>({...e,laneId:null})),scale=Scale.svg(es,tl,system,domain,{width,legend:options.legend,spans:options.spans}),height=Number(scale.match(/height="(\d+)" role/)[1]);let y=100+height,body=`<text x="35" y="38" font-size="25" font-weight="600">${esc(options.title)}</text><text x="35" y="70" font-size="14">${esc(options.subtitle)}</text><g transform="translate(0 90)">${scale.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'')}</g>`;
for(const e of events){const pieces=[];if(fields.has('date'))pieces.push(T.label(e.temporal,system));for(const [field,value]of [['summary',e.summary],['markdown',textMarkdown(e.markdown)],['place',e.place?'Lieu : '+e.place:''],['tags',e.tags.length?'Tags : '+e.tags.join(', '):''],['lane',context.lane(e,timeline)],['links',e.links],['relations',context.relations(e,timeline)]])if(fields.has(field)&&value)pieces.push(value);if(options.sources)pieces.push(context.source(e));const media=e.mediaIds.map(id=>project.media.find(m=>m.id===id)).filter(Boolean);if(fields.has('media'))pieces.push(media.map(m=>'Fichier : '+m.name+(m.caption?' — '+m.caption:'')).join('\n'));if(!pieces.filter(Boolean).length&&!options.media)continue;y+=28;body+=`<text x="35" y="${y}" font-size="17" font-weight="600">${esc(e.title)}</text>`;for(const line of wrap(pieces.filter(Boolean).join('\n'),118)){y+=19;body+=`<text x="35" y="${y}" font-size="13">${esc(line)}</text>`}if(options.media){const m=media.find(m=>!m.remoteUrl&&m.mimeType.startsWith('image/'));if(m){const url=await S.dataURL(context.assets.get(m.storageRef));y+=15;body+=`<image x="35" y="${y}" width="350" height="180" preserveAspectRatio="xMinYMid meet" href="${esc(url)}"/><title>${esc(m.alt||e.title)}</title>`;y+=180;}}}
const physical=options.format==='A3'?297:210,mm=options.orientation==='landscape'?(options.format==='A3'?420:297):physical;return `<svg xmlns="http://www.w3.org/2000/svg" width="${mm-2*options.margin}mm" height="${(y+35)/width*(mm-2*options.margin)}mm" viewBox="0 0 ${width} ${y+35}" role="img" aria-label="${esc(options.title)}"><rect width="100%" height="100%" fill="#fff"/><style>text{font-family:system-ui,sans-serif;fill:#283530}</style>${body}</svg>`;}
async function png(svgText,pixels=2048){const match=svgText.match(/viewBox="0 0 (\d+) ([\d.]+)"/),width=Number(match[1]),height=Number(match[2]),targetHeight=Math.round(pixels*height/width);if(pixels<300||pixels>4096||targetHeight>16384||pixels*targetHeight>32*1024*1024)throw Error('Cette publication est trop longue pour un PNG. Réduis la plage ou utilise le SVG/HTML.');const url=URL.createObjectURL(new Blob([svgText],{type:'image/svg+xml'})),image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('Rasterisation impossible.'));image.src=url;});const canvas=document.createElement('canvas');canvas.width=pixels;canvas.height=targetHeight;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,pixels,targetHeight);ctx.drawImage(image,0,0,pixels,targetHeight);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('PNG indisponible.')),'image/png'));}finally{URL.revokeObjectURL(url)}}
return {texEscape,markdownTeX,svg,png,wrap,textMarkdown};
})();
